#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import shutil
import os
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
PROBES_FILE = ROOT / "test" / "tier1_api_surface_probes.json"
CACHE_ROOT = ROOT / "test" / ".cache"
WORK_ROOT = CACHE_ROOT / "tier1-api-surface-smoke"
OUT_DIR = WORK_ROOT / "out"
SRC_DIR = WORK_ROOT / "src"
MAIN_HX = SRC_DIR / "Main.hx"
HXML_FILE = WORK_ROOT / "compile.hxml"
REPORT_FILE = CACHE_ROOT / "tier1_api_surface_report.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compile generated Tier1 API-surface probes (portable profile) and cargo-check the emitted crate."
    )
    parser.add_argument("--haxe-bin", default="", help="Haxe binary override")
    parser.add_argument("--cargo-bin", default="cargo", help="Cargo binary override")
    parser.add_argument("--keep", action="store_true", help="Keep generated workspace after run")
    parser.add_argument("--print-main", action="store_true", help="Print generated Main.hx")
    return parser.parse_args()


def fail(message: str) -> None:
    raise SystemExit(message)


def load_probes() -> list[dict[str, Any]]:
    try:
        payload = json.loads(PROBES_FILE.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        fail(f"missing probes file: {PROBES_FILE.relative_to(ROOT)}")
        raise exc
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON in {PROBES_FILE.relative_to(ROOT)}: {exc}")
        raise exc

    if not isinstance(payload, dict):
        fail("probes file root must be an object")
    if payload.get("schema_version") != 1:
        fail("probes file schema_version must be 1")

    probes = payload.get("probes")
    if not isinstance(probes, list) or len(probes) == 0:
        fail("probes file must include a non-empty probes array")

    ids: list[str] = []
    for probe in probes:
        if not isinstance(probe, dict):
            fail("each probe entry must be an object")
        probe_id = probe.get("id")
        body = probe.get("body")
        if not isinstance(probe_id, str) or not probe_id:
            fail("probe id must be a non-empty string")
        if not isinstance(body, list) or len(body) == 0:
            fail(f"probe `{probe_id}` body must be a non-empty array")
        for line in body:
            if not isinstance(line, str):
                fail(f"probe `{probe_id}` body lines must be strings")
        ids.append(probe_id)

    if ids != sorted(ids):
        fail("probe ids must be sorted lexicographically for deterministic output")
    if len(ids) != len(set(ids)):
        fail("probe ids must be unique")
    return probes


def generate_main_hx(probes: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("/**")
    lines.append(" * Generated by `test/run-tier1-api-surface-smoke.py`.")
    lines.append(" *")
    lines.append(" * Why:")
    lines.append(" * This file forces direct typed references to high-risk Tier1 stdlib APIs.")
    lines.append(" *")
    lines.append(" * How:")
    lines.append(" * Each probe body exercises one module surface. CI compiles this file under portable")
    lines.append(" * and runs `cargo check` on the generated crate so declared-but-unimplemented runtime")
    lines.append(" * bindings fail fast.")
    lines.append(" */")
    lines.append("class Main {")
    lines.append("\tstatic function main() {")
    lines.append("\t\tvar checksum = 0;")
    for probe in probes:
        lines.append(f"\t\tchecksum += {probe['id']}();")
    lines.append("\t\tSys.println('tier1-surface-checksum=' + checksum);")
    lines.append("\t}")
    lines.append("")
    for probe in probes:
        lines.append(f"\tstatic function {probe['id']}():Int {{")
        for body_line in probe["body"]:
            lines.append(f"\t\t{body_line}")
        lines.append("\t}")
        lines.append("")
    lines.append("}")
    return "\n".join(lines).rstrip() + "\n"


def write_workspace(main_hx: str) -> None:
    if WORK_ROOT.exists():
        shutil.rmtree(WORK_ROOT)
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    MAIN_HX.write_text(main_hx, encoding="utf-8")
    hxml_lines = [
        "-cp src",
        "-lib reflaxe.rust",
        "-D reflaxe_rust_profile=portable",
        "-D reflaxe_rust_strict_examples",
        "-D rust_emit_upstream_std",
        f"-D rust_output={OUT_DIR.as_posix()}",
        "-D rust_no_build",
        "-D no-traces",
        "-D no_traces",
        "-main Main",
    ]
    HXML_FILE.write_text("\n".join(hxml_lines) + "\n", encoding="utf-8")


def run_command(cmd: list[str], cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=merged_env)


def choose_haxe_bin(cli_value: str) -> str:
    if cli_value:
        return cli_value
    env_value = (Path.cwd() / "node_modules" / ".bin" / "haxe").resolve()
    if env_value.exists():
        return str(env_value)
    return "haxe"


def write_report(probe_count: int, haxe_bin: str, cargo_bin: str, haxe_code: int, cargo_fmt_code: int, cargo_check_code: int) -> None:
    CACHE_ROOT.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": 1,
        "probe_count": probe_count,
        "haxe_bin": haxe_bin,
        "cargo_bin": cargo_bin,
        "workspace": WORK_ROOT.relative_to(ROOT).as_posix(),
        "out_dir": OUT_DIR.relative_to(ROOT).as_posix(),
        "haxe_exit_code": haxe_code,
        "cargo_fmt_exit_code": cargo_fmt_code,
        "cargo_check_exit_code": cargo_check_code,
        "status": "ok" if haxe_code == 0 and cargo_fmt_code == 0 and cargo_check_code == 0 else "failed",
    }
    REPORT_FILE.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    probes = load_probes()
    main_hx = generate_main_hx(probes)
    write_workspace(main_hx)

    if args.print_main:
        print(main_hx, end="")

    haxe_bin = choose_haxe_bin(args.haxe_bin)
    cargo_bin = args.cargo_bin

    haxe_proc = run_command([haxe_bin, "compile.hxml"], cwd=WORK_ROOT)
    if haxe_proc.returncode != 0:
        write_report(len(probes), haxe_bin, cargo_bin, haxe_proc.returncode, -1, -1)
        print(haxe_proc.stdout, end="")
        print(haxe_proc.stderr, end="")
        return haxe_proc.returncode

    cargo_fmt_proc = run_command([cargo_bin, "fmt"], cwd=OUT_DIR)
    if cargo_fmt_proc.returncode != 0:
        write_report(len(probes), haxe_bin, cargo_bin, 0, cargo_fmt_proc.returncode, -1)
        print(cargo_fmt_proc.stdout, end="")
        print(cargo_fmt_proc.stderr, end="")
        return cargo_fmt_proc.returncode

    target_dir = CACHE_ROOT / "tier1-api-surface-target"
    cargo_check_proc = run_command([cargo_bin, "check", "-q"], cwd=OUT_DIR, env={"CARGO_TARGET_DIR": str(target_dir)})
    if cargo_check_proc.returncode != 0:
        write_report(len(probes), haxe_bin, cargo_bin, 0, 0, cargo_check_proc.returncode)
        print(cargo_check_proc.stdout, end="")
        print(cargo_check_proc.stderr, end="")
        return cargo_check_proc.returncode

    write_report(len(probes), haxe_bin, cargo_bin, 0, 0, 0)
    print(f"[tier1-surface] ok ({len(probes)} probes)")
    print(f"[tier1-surface] report: {REPORT_FILE.relative_to(ROOT)}")

    if not args.keep:
        shutil.rmtree(WORK_ROOT, ignore_errors=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
