// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x078ae5f9u32;

#[derive(Debug)]
pub struct LabelProviderGroupImpl {}

impl LabelProviderGroupImpl {
    pub fn get(
        this1: hxrt::array::Array<crate::HxRef<crate::label_provider::LabelProvider>>,
        index: i32,
    ) -> crate::HxRef<crate::label_provider::LabelProvider> {
        return this1.get_unchecked(index as usize);
    }
}
