// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xe4f5b044u32;

#[derive(Debug)]
pub struct DebugLeaf {
    pub value: i32,
}

impl DebugLeaf {
    pub fn new(value: i32) -> crate::HxRef<crate::debug_leaf::DebugLeaf> {
        let self_: crate::HxRef<crate::debug_leaf::DebugLeaf> =
            crate::HxRef::new(DebugLeaf { value: value });
        return self_;
    }
}
