// Generated by reflaxe.rust

#![deny(warnings)]
#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod _main_label_provider_group_impl_;
mod debug_leaf;
mod debug_node;
mod debug_owner;
mod erased_type_owner;
mod fixed_label_source;
mod haxe_call_stack_call_stack_impl_;
mod haxe_exception;
mod haxe_stack_item;
mod label_group_owner;
mod label_owner;
mod label_provider;
mod label_source;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x1a1b6d30u32 => expected == 0x9c412e24u32,
        _ => false,
    }
}

fn main() {
    let source: crate::HxRc<dyn crate::label_source::LabelSource + Send + Sync> = {
        let __tmp =
            crate::fixed_label_source::FixedLabelSource::new(hxrt::string::HxString::from("ready"));
        let __up: crate::HxRc<dyn crate::label_source::LabelSource + Send + Sync> =
            __tmp.as_arc_opt().unwrap().clone();
        __up
    };
    let owner: crate::HxRef<crate::label_owner::LabelOwner> = crate::label_owner::LabelOwner::new(
        crate::label_provider::LabelProvider::new(source.clone()),
    );
    let group_owner: crate::HxRef<crate::label_group_owner::LabelGroupOwner> =
        crate::label_group_owner::LabelGroupOwner::new(hxrt::array::Array::<
            crate::HxRef<crate::label_provider::LabelProvider>,
        >::from_vec(vec![
            crate::label_provider::LabelProvider::new(source.clone()),
        ]));
    let erased_type_owner: crate::HxRef<crate::erased_type_owner::ErasedTypeOwner> =
        crate::erased_type_owner::ErasedTypeOwner::new(0xf16d2920u32);
    let debug_owner: crate::HxRef<crate::debug_owner::DebugOwner> =
        crate::debug_owner::DebugOwner::new(crate::debug_leaf::DebugLeaf::new(1));
    let debug_node: crate::HxRef<crate::debug_node::DebugNode> =
        crate::debug_node::DebugNode::new(crate::HxRef::<crate::debug_node::DebugNode>::null());
    if crate::label_owner::LabelOwner::label(&*owner) != hxrt::string::HxString::from("ready")
        || crate::label_group_owner::LabelGroupOwner::label(&*group_owner)
            != hxrt::string::HxString::from("ready")
        || ({
            let __b = erased_type_owner.borrow();
            __b.kind.clone()
        }) != 0xf16d2920u32
        || ({
            let __hx_recv = {
                let __b = debug_owner.borrow();
                __b.leaf.clone()
            };
            let __b = __hx_recv.borrow();
            __b.value
        }) != 1
        || !({
            let __b = debug_node.borrow();
            __b.next.clone()
        })
        .is_null()
    {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "unexpected label",
        )));
    }
}
