// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod person;
mod rust_serde_serde_json;
mod sys;

fn main() {
    let person: crate::HxRef<crate::person::Person> =
        crate::person::Person::new(String::from("Alice"), 30);
    let json: String = crate::rust_serde_serde_json::SerdeJson::to_string(person);
    crate::sys::Sys::println(hxrt::dynamic::from(json.clone()));
}
