// Generated by reflaxe.rust (POC)

use crate::HxRef;
use std::cell::RefCell;
use std::rc::Rc;

pub const __HX_TYPE_ID: u32 = 0x1d340e64u32;

#[derive(Debug, serde::Serialize, serde::Deserialize)]

pub struct Person {
    pub name: String,
    pub age: i32,
}

impl Person {
    pub fn new(name: String, age: i32) -> HxRef<Person> {
        let self_: HxRef<Person> = Rc::new(RefCell::new(Person {
            name: String::new(),
            age: 0,
        }));
        {
            let __tmp = name;
            self_.borrow_mut().name = __tmp.clone();
            __tmp
        };
        {
            let __tmp = age;
            self_.borrow_mut().age = __tmp.clone();
            __tmp
        };
        return self_;
    }
}
