// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x1d340e64u32;

#[derive(Debug, serde::Serialize, serde::Deserialize)]

pub struct Person {
    pub name: String,
    pub age: i32,
}

impl Person {
    pub fn new(name: String, age: i32) -> crate::HxRef<crate::person::Person> {
        let self_: crate::HxRef<crate::person::Person> =
            std::rc::Rc::new(std::cell::RefCell::new(Person {
                name: String::new(),
                age: 0,
            }));
        {
            let __tmp = name;
            self_.borrow_mut().name = __tmp.clone();
            __tmp
        };
        {
            let __tmp = age;
            self_.borrow_mut().age = __tmp.clone();
            __tmp
        };
        return self_;
    }
}
