// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x111fa3c1u32;

#[derive(Debug)]

pub struct Animal {
    pub age: i32,
}

impl Animal {
    pub fn new() -> crate::HxRef<crate::animal::Animal> {
        let self_: crate::HxRef<crate::animal::Animal> = crate::HxRef::new(Animal { age: 0 });
        return self_;
    }
}

pub trait AnimalTrait: Send + Sync {
    fn __hx_get_age(&self) -> i32;
    fn __hx_set_age(&self, v: i32);
    fn __hx_type_id(&self) -> u32;
}

impl crate::animal::AnimalTrait for crate::HxRefCell<Animal> {
    fn __hx_get_age(&self) -> i32 {
        self.borrow().age
    }
    fn __hx_set_age(&self, v: i32) {
        self.borrow_mut().age = v;
    }
    fn __hx_type_id(&self) -> u32 {
        crate::animal::__HX_TYPE_ID
    }
}
