// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod animal;
mod dog;
mod sys;
use crate::animal::Animal;
use crate::dog::Dog;
use crate::sys::Sys;

fn main() {
    let mut a: std::rc::Rc<dyn crate::animal::AnimalTrait> = Dog::new();
    {
        let __tmp = 3;
        a.__hx_set_age(__tmp);
        __tmp
    };
    println!("{}", a.__hx_get_age());
}
