// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xb3d8debcu32;

#[derive(Clone, Debug, PartialEq)]
pub enum Constraint {
    Fixed(i32),
    Percent(i32),
    Min(i32),
    Max(i32),
    Fill,
}
