/**
 * Why: The four machine-readable reports need one real compiler-emission fixture.
 * What: Keeps the program deliberately small while exercising a normal metal compilation.
 * How: The snapshot variant enables every JSON report and the schema guard validates the emitted
 * files; report contents are generated by the compiler rather than handwritten test data.
 */
class Main {
	static function main():Void {
		var value:Int = 41;
		trace(value + 1);
	}
}
