// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x387ca64du32;

#[derive(Debug)]

pub struct Accumulator {
    pub text: hxrt::string::HxString,
}

impl Accumulator {
    pub fn new() -> crate::HxRef<crate::accumulator::Accumulator> {
        let self_: crate::HxRef<crate::accumulator::Accumulator> = crate::HxRef::new(Accumulator {
            text: hxrt::string::HxString::from(""),
        });
        return self_;
    }

    pub fn append(
        self_: &crate::HxRefCell<Accumulator>,
        value: hxrt::string::HxString,
    ) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::accumulator::Accumulator> = self_.self_ref();
        return hxrt::string::HxString::from({
            let __rhs = value;
            let __tmp = {
                let __b = self_.borrow();
                hxrt::string::HxString::from(format!("{}{}", &__b.text, __rhs))
            };
            self_.borrow_mut().text = __tmp.clone();
            __tmp
        });
    }
}
