// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xd7e07825u32;

#[derive(Debug)]

pub struct ObjectMap<
    K: hxrt::hxref::HxRefLike + Clone + Send + Sync + 'static + std::fmt::Debug,
    V: Clone + Send + Sync + 'static + std::fmt::Debug,
> {
    pub keys_map: std::collections::HashMap<hxrt::string::HxString, K>,
    pub values_map: std::collections::HashMap<hxrt::string::HxString, V>,
}

impl<
        K: hxrt::hxref::HxRefLike + Clone + Send + Sync + 'static + std::fmt::Debug,
        V: Clone + Send + Sync + 'static + std::fmt::Debug,
    > ObjectMap<K, V>
{
    pub fn new() -> crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> {
        let self_: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> =
            crate::HxRef::new(ObjectMap {
                keys_map: std::collections::HashMap::<hxrt::string::HxString, K>::new(),
                values_map: std::collections::HashMap::<hxrt::string::HxString, V>::new(),
            });
        return self_;
    }

    fn key_id(_self_: &crate::HxRefCell<ObjectMap<K, V>>, key: K) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyId(&key),
        );
    }

    pub fn set(self_: &crate::HxRefCell<ObjectMap<K, V>>, key: K, value: V) {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        let id: hxrt::string::HxString = hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyId(&key),
        );
        crate::map_storage_tools_nullable::MapStorageTools::objectMapSet(
            __hx_this.clone(),
            hxrt::string::HxString::from(id),
            key,
            value,
        );
    }

    pub fn get(self_: &crate::HxRefCell<ObjectMap<K, V>>, key: K) -> Option<V> {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        let id: hxrt::string::HxString = hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyId(&key),
        );
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapGetCloned(
            __hx_this.clone(),
            hxrt::string::HxString::from(id),
        );
    }

    pub fn exists(self_: &crate::HxRefCell<ObjectMap<K, V>>, key: K) -> bool {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        let id: hxrt::string::HxString = hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyId(&key),
        );
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapExists(
            __hx_this.clone(),
            hxrt::string::HxString::from(id),
        );
    }

    pub fn remove(self_: &crate::HxRefCell<ObjectMap<K, V>>, key: K) -> bool {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        let id: hxrt::string::HxString = hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyId(&key),
        );
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapRemoveExists(
            __hx_this.clone(),
            hxrt::string::HxString::from(id),
        );
    }

    pub fn keys(self_: &crate::HxRefCell<ObjectMap<K, V>>) -> hxrt::iter::Iter<K> {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapKeysOwned(
            __hx_this.clone(),
        );
    }

    pub fn iterator(self_: &crate::HxRefCell<ObjectMap<K, V>>) -> hxrt::iter::Iter<V> {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapValuesOwned(
            __hx_this.clone(),
        );
    }

    pub fn key_value_iterator(
        self_: &crate::HxRefCell<ObjectMap<K, V>>,
    ) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>> {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        return crate::map_storage_tools_nullable::MapStorageTools::objectMapKeyValuesOwned(
            __hx_this.clone(),
        );
    }

    pub fn copy(
        self_: &crate::HxRefCell<ObjectMap<K, V>>,
    ) -> crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        let out: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> =
            crate::haxe_ds_object_map::ObjectMap::<K, V>::new();
        crate::map_storage_tools_nullable::MapStorageTools::objectMapCloneInto(
            out.clone(),
            __hx_this.clone(),
        );
        return out;
    }

    pub fn to_string(self_: &crate::HxRefCell<ObjectMap<K, V>>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        return hxrt::string::HxString::from(
            crate::map_storage_tools_nullable::MapStorageTools::objectMapDebugString(
                __hx_this.clone(),
            ),
        );
    }

    pub fn clear(self_: &crate::HxRefCell<ObjectMap<K, V>>) {
        let __hx_this: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<K, V>> = self_.self_ref();
        crate::map_storage_tools_nullable::MapStorageTools::objectMapClear(__hx_this.clone());
    }
}

impl<
        K: hxrt::hxref::HxRefLike + Clone + Send + Sync + 'static + std::fmt::Debug,
        V: Clone + Send + Sync + 'static + std::fmt::Debug,
    > crate::haxe_i_map::IMap<K, V> for crate::HxRefCell<ObjectMap<K, V>>
{
    fn get(&self, k: K) -> Option<V> {
        ObjectMap::<K, V>::get(self, k)
    }
    fn set(&self, k: K, v: V) -> () {
        ObjectMap::<K, V>::set(self, k, v)
    }
    fn exists(&self, k: K) -> bool {
        ObjectMap::<K, V>::exists(self, k)
    }
    fn remove(&self, k: K) -> bool {
        ObjectMap::<K, V>::remove(self, k)
    }
    fn keys(&self) -> hxrt::iter::Iter<K> {
        ObjectMap::<K, V>::keys(self)
    }
    fn iterator(&self) -> hxrt::iter::Iter<V> {
        ObjectMap::<K, V>::iterator(self)
    }
    fn key_value_iterator(&self) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>> {
        ObjectMap::<K, V>::key_value_iterator(self)
    }
    fn copy(&self) -> crate::HxRc<dyn crate::haxe_i_map::IMap<K, V> + Send + Sync> {
        let __tmp = ObjectMap::<K, V>::copy(self);
        let __up: crate::HxRc<dyn crate::haxe_i_map::IMap<K, V> + Send + Sync> =
            match __tmp.as_arc_opt() {
                Some(__rc) => __rc.clone(),
                None => hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access"))),
            };
        __up
    }
    fn to_string(&self) -> hxrt::string::HxString {
        ObjectMap::<K, V>::to_string(self)
    }
    fn clear(&self) -> () {
        ObjectMap::<K, V>::clear(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::haxe_ds_object_map::__HX_TYPE_ID
    }
}
