// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod rust_borrow;
mod rust_str_tools;
mod rust_string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let s: String = String::from("hello world");
    let ok: bool = {
        let haystack: &String = &s;
        {
            let _hx_ref: &String = &String::from("world");
            {
                let needle: &str = _hx_ref;
                crate::rust_string_tools::StringTools::contains(haystack, needle)
            }
        }
    };
    println!("{}", hxrt::dynamic::from(ok));
}
