// Generated by reflaxe.rust

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod fp_helper;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int32_int32_impl_;
mod haxe_int64_helper;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_stack_item;
mod int32_tools;
mod map_storage_tools_nullable;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;
mod sys_thread_deque;
mod sys_thread_elastic_thread_pool;
mod sys_thread_elastic_thread_pool_worker;
mod sys_thread_event_loop;
mod sys_thread_i_thread_pool;
mod sys_thread_lock;
mod sys_thread_mutex;
mod sys_thread_next_event_time;
mod sys_thread_thread;
mod sys_thread_thread_pool_exception;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => matches!(expected, 0x44f4c432u32),
        0x39e0cd5bu32 => matches!(expected, 0x44f4c432u32),
        0xd7e07825u32 => matches!(expected, 0x44f4c432u32),
        0x181f937bu32 => matches!(expected, 0x44f4c432u32),
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        0x4a39169bu32 => matches!(expected, 0x7cc99a83u32),
        0x06e5ab1du32 => matches!(expected, 0xad5d98ceu32),
        _ => false,
    }
}

fn main() {
    let pool: crate::HxRef<crate::sys_thread_elastic_thread_pool::ElasticThreadPool> =
        crate::sys_thread_elastic_thread_pool::ElasticThreadPool::new(2, 0.1);
    let done: crate::HxRef<crate::sys_thread_lock::Lock> = crate::sys_thread_lock::Lock::new();
    let mutex: crate::HxRef<crate::sys_thread_mutex::Mutex> = crate::sys_thread_mutex::Mutex::new();
    let state1_0: crate::HxRef<i32> = crate::HxRef::new(0);
    {
        let __tmp = 0;
        *state1_0.borrow_mut() = __tmp;
        __tmp
    };
    {
        {
            let done1: crate::HxRef<crate::sys_thread_lock::Lock> = done.clone();
            let mutex1: crate::HxRef<crate::sys_thread_mutex::Mutex> = mutex.clone();
            crate::sys_thread_elastic_thread_pool::ElasticThreadPool::run(&*pool, {
                let done1 = done1.clone();
                let mutex1 = mutex1.clone();
                let state1_0 = state1_0.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    crate::sys_thread_mutex::Mutex::acquire(&*mutex1);
                    {
                        let __tmp = *state1_0.borrow() + 1;
                        *state1_0.borrow_mut() = __tmp;
                        __tmp
                    };
                    let count: i32 = *state1_0.borrow();
                    crate::sys_thread_mutex::Mutex::release(&*mutex1);
                    if count == 4 {
                        crate::sys_thread_lock::Lock::release(&*done1);
                    }
                });
                crate::HxDynRef::new(__rc)
            });
        }
        {
            let done1_2: crate::HxRef<crate::sys_thread_lock::Lock> = done.clone();
            let mutex1_2: crate::HxRef<crate::sys_thread_mutex::Mutex> = mutex.clone();
            crate::sys_thread_elastic_thread_pool::ElasticThreadPool::run(&*pool, {
                let done1_2 = done1_2.clone();
                let mutex1_2 = mutex1_2.clone();
                let state1_0 = state1_0.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    crate::sys_thread_mutex::Mutex::acquire(&*mutex1_2);
                    {
                        let __tmp = *state1_0.borrow() + 1;
                        *state1_0.borrow_mut() = __tmp;
                        __tmp
                    };
                    let count: i32 = *state1_0.borrow();
                    crate::sys_thread_mutex::Mutex::release(&*mutex1_2);
                    if count == 4 {
                        crate::sys_thread_lock::Lock::release(&*done1_2);
                    }
                });
                crate::HxDynRef::new(__rc)
            });
        }
        {
            let done1_3: crate::HxRef<crate::sys_thread_lock::Lock> = done.clone();
            let mutex1_3: crate::HxRef<crate::sys_thread_mutex::Mutex> = mutex.clone();
            crate::sys_thread_elastic_thread_pool::ElasticThreadPool::run(&*pool, {
                let done1_3 = done1_3.clone();
                let mutex1_3 = mutex1_3.clone();
                let state1_0 = state1_0.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    crate::sys_thread_mutex::Mutex::acquire(&*mutex1_3);
                    {
                        let __tmp = *state1_0.borrow() + 1;
                        *state1_0.borrow_mut() = __tmp;
                        __tmp
                    };
                    let count: i32 = *state1_0.borrow();
                    crate::sys_thread_mutex::Mutex::release(&*mutex1_3);
                    if count == 4 {
                        crate::sys_thread_lock::Lock::release(&*done1_3);
                    }
                });
                crate::HxDynRef::new(__rc)
            });
        }
        {
            let done1_4: crate::HxRef<crate::sys_thread_lock::Lock> = done.clone();
            let mutex1_4: crate::HxRef<crate::sys_thread_mutex::Mutex> = mutex.clone();
            crate::sys_thread_elastic_thread_pool::ElasticThreadPool::run(&*pool, {
                let done1_4 = done1_4.clone();
                let mutex1_4 = mutex1_4.clone();
                let state1_0 = state1_0.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    crate::sys_thread_mutex::Mutex::acquire(&*mutex1_4);
                    {
                        let __tmp = *state1_0.borrow() + 1;
                        *state1_0.borrow_mut() = __tmp;
                        __tmp
                    };
                    let count: i32 = *state1_0.borrow();
                    crate::sys_thread_mutex::Mutex::release(&*mutex1_4);
                    if count == 4 {
                        crate::sys_thread_lock::Lock::release(&*done1_4);
                    }
                });
                crate::HxDynRef::new(__rc)
            });
        }
    }
    crate::sys_thread_lock::Lock::wait(&*done, None);
    crate::sys::Sys::sleep(0.25);
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}{}{}",
        "done=",
        hxrt::dynamic::from(*state1_0.borrow()).to_haxe_string(),
        ";threads=",
        hxrt::dynamic::from(
            crate::sys_thread_elastic_thread_pool::ElasticThreadPool::get_threads_count(&*pool)
        )
        .to_haxe_string()
    ))));
    crate::sys_thread_elastic_thread_pool::ElasticThreadPool::shutdown(&*pool);
}
