// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xe2fc722cu32;

pub struct Worker {
    pub task: crate::HxDynRef<dyn Fn() + Send + Sync>,
    pub dead: bool,
    death_mutex: crate::HxRef<crate::sys_thread_mutex::Mutex>,
    waiter: crate::HxRef<crate::sys_thread_lock::Lock>,
    queue: crate::HxRef<crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>>,
    timeout: f64,
    is_shutdown: bool,
}

impl Worker {
    pub fn new(
        queue: crate::HxRef<
            crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>,
        >,
        timeout: f64,
    ) -> crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker> {
        let self_: crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker> =
            crate::HxRef::new(Worker {
                task: crate::HxDynRef::<dyn Fn() + Send + Sync>::null(),
                dead: false,
                death_mutex: crate::sys_thread_mutex::Mutex::new(),
                waiter: crate::sys_thread_lock::Lock::new(),
                queue: queue,
                timeout: timeout,
                is_shutdown: false,
            });
        crate::sys_thread_elastic_thread_pool_worker::Worker::start(self_.clone());
        return self_;
    }

    pub fn wakeup(
        worker: crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker>,
        task: crate::HxDynRef<dyn Fn() + Send + Sync>,
    ) {
        crate::sys_thread_mutex::Mutex::acquire(
            &*({
                let __b = worker.borrow();
                __b.death_mutex.clone()
            }),
        );
        if {
            let __b = worker.borrow();
            __b.dead
        } {
            crate::sys_thread_elastic_thread_pool_worker::Worker::start(worker.clone());
        }
        {
            let __tmp = task;
            worker.borrow_mut().task = __tmp.clone();
            __tmp
        };
        crate::sys_thread_lock::Lock::release(
            &*({
                let __b = worker.borrow();
                __b.waiter.clone()
            }),
        );
        crate::sys_thread_mutex::Mutex::release(
            &*({
                let __b = worker.borrow();
                __b.death_mutex.clone()
            }),
        );
    }

    pub fn shutdown(worker: crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker>) {
        {
            let __tmp = true;
            worker.borrow_mut().is_shutdown = __tmp;
            __tmp
        };
        crate::sys_thread_lock::Lock::release(
            &*({
                let __b = worker.borrow();
                __b.waiter.clone()
            }),
        );
    }

    fn start(worker: crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker>) {
        {
            let __tmp = false;
            worker.borrow_mut().dead = __tmp;
            __tmp
        };
        crate::sys_thread_thread::Thread::create({
            let worker = worker.clone();
            let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                crate::sys_thread_elastic_thread_pool_worker::Worker::loop_(worker.clone());
            });
            crate::HxDynRef::new(__rc)
        });
    }

    fn loop_(worker: crate::HxRef<crate::sys_thread_elastic_thread_pool_worker::Worker>) {
        match hxrt::exception::catch_unwind(|| {
            while crate::sys_thread_lock::Lock::wait(&*({
                let __b = worker.borrow();
                __b.waiter.clone()
            }), Some({
                let __b = worker.borrow();
                __b.timeout
            })) {
                {
                    let _g: crate::HxDynRef<dyn Fn() + Send + Sync> = {
                        let __b = worker.borrow();
                        __b.task.clone()
                    };
                    if _g.is_null() {
                        if {
                            let __b = worker.borrow();
                            __b.is_shutdown
                        } {
                            break;
                        }
                    } else {
                        let fn_: crate::HxDynRef<dyn Fn() + Send + Sync> = _g.clone();
                        {
                            fn_();
                            loop {
                                {
                                    let _g_2: crate::HxDynRef<dyn Fn() + Send + Sync> = {
                                        let __hx_opt = crate::sys_thread_deque::Deque::pop(&*({
                                            let __b = worker.borrow();
                                            __b.queue.clone()
                                        }), false);
                                        match __hx_opt {
                                            Some(__v) => __v,
                                            None => crate::HxDynRef::null(),
                                        }
                                    };
                                    if _g_2.is_null() {
                                        break;
                                    } else {
                                        let fn_2: crate::HxDynRef<dyn Fn() + Send + Sync> = _g_2.clone();
                                        fn_2();
                                    }
                                }
                            }
                            {
                                let __tmp = crate::HxDynRef::<dyn Fn() + Send + Sync>::null();
                                worker.borrow_mut().task = __tmp.clone();
                                __tmp
                            };
                        }
                    }
                }
            }
            crate::sys_thread_mutex::Mutex::acquire(&*({
                let __b = worker.borrow();
                __b.death_mutex.clone()
            }));
            if !({
                let __b = worker.borrow();
                __b.task.clone()
            }).is_null() {
                crate::sys_thread_elastic_thread_pool_worker::Worker::start(worker.clone());
            } else {
                {
                    let __tmp = true;
                    worker.borrow_mut().dead = __tmp;
                    __tmp
                };
            }
            crate::sys_thread_mutex::Mutex::release(&*({
                let __b = worker.borrow();
                __b.death_mutex.clone()
            }));
        }) {
            Ok(__hx_ok) => __hx_ok,
            Err(__hx_ex) => match __hx_ex.type_id() {
                Some(__actual_type_id) => if crate::__hx_is_subtype_type_id(__actual_type_id, 0xad5d98ceu32) { if __actual_type_id == 0xad5d98ceu32 { match __hx_ex.downcast::<crate::HxRef<crate::haxe_exception::Exception>>() {
                    Ok(__hx_box) => {
                        let e: crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync> = {
                            let __tmp = *__hx_box;
                            let __up: crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync> = match __tmp.as_arc_opt() {
                                Some(__rc) => __rc.clone(),
                                None => hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access"))),
                            };
                            __up
                        };
                        {
                            let __tmp = crate::HxDynRef::<dyn Fn() + Send + Sync>::null();
                            worker.borrow_mut().task = __tmp.clone();
                            __tmp
                        };
                        crate::sys_thread_elastic_thread_pool_worker::Worker::start(worker.clone());
                        hxrt::exception::throw({
                            let __hx_box = e;
                            let __hx_box_type_id = __hx_box.__hx_type_id();
                            hxrt::dynamic::from_ref_with_type_id(__hx_box, __hx_box_type_id)
                        });
                    }
                    Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
                } } else { if __actual_type_id == 0x06e5ab1du32 { match __hx_ex.downcast::<crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException>>() {
                    Ok(__hx_box) => {
                        let e: crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync> = {
                            let __tmp = *__hx_box;
                            let __up: crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync> = match __tmp.as_arc_opt() {
                                Some(__rc) => __rc.clone(),
                                None => hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access"))),
                            };
                            __up
                        };
                        {
                            let __tmp = crate::HxDynRef::<dyn Fn() + Send + Sync>::null();
                            worker.borrow_mut().task = __tmp.clone();
                            __tmp
                        };
                        crate::sys_thread_elastic_thread_pool_worker::Worker::start(worker.clone());
                        hxrt::exception::throw({
                            let __hx_box = e;
                            let __hx_box_type_id = __hx_box.__hx_type_id();
                            hxrt::dynamic::from_ref_with_type_id(__hx_box, __hx_box_type_id)
                        });
                    }
                    Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
                } } else { hxrt::exception::rethrow(__hx_ex) } } } else { hxrt::exception::rethrow(__hx_ex) },
                None => match __hx_ex.downcast::<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>>() {
                    Ok(__hx_box) => {
                        let e: crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync> = *__hx_box;
                        {
                            let __tmp = crate::HxDynRef::<dyn Fn() + Send + Sync>::null();
                            worker.borrow_mut().task = __tmp.clone();
                            __tmp
                        };
                        crate::sys_thread_elastic_thread_pool_worker::Worker::start(worker.clone());
                        hxrt::exception::throw({
                            let __hx_box = e;
                            let __hx_box_type_id = __hx_box.__hx_type_id();
                            hxrt::dynamic::from_ref_with_type_id(__hx_box, __hx_box_type_id)
                        });
                    }
                    Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
                },
            },
        };
    }
}
