// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x06e5ab1du32;

pub struct ThreadPoolException {
    _message: hxrt::string::HxString,
    _previous: Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>>,
    _native: hxrt::dynamic::Dynamic,
    _stack: hxrt::array::Array<crate::haxe_stack_item::StackItem>,
}

impl ThreadPoolException {
    pub fn new(
        message: hxrt::string::HxString,
        previous: Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>>,
        native: hxrt::dynamic::Dynamic,
    ) -> crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> {
        let self_: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            crate::HxRef::new(ThreadPoolException {
                _message: hxrt::string::HxString::null(),
                _previous: None,
                _native: hxrt::dynamic::Dynamic::null(),
                _stack: hxrt::array::Array::<crate::haxe_stack_item::StackItem>::new(),
            });
        let __hx_super_0_0: hxrt::string::HxString = hxrt::string::HxString::from(message);
        let __hx_super_0_1: Option<
            crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>,
        > = previous;
        let __hx_super_0_2: hxrt::dynamic::Dynamic = native.clone();
        {
            let __tmp = __hx_super_0_0.clone();
            self_.borrow_mut()._message = hxrt::string::HxString::from(__tmp.clone());
            __tmp
        };
        {
            let __tmp = __hx_super_0_1.clone();
            self_.borrow_mut()._previous = __tmp.clone();
            __tmp
        };
        {
            let __tmp = __hx_super_0_2.clone();
            self_.borrow_mut()._native = __tmp.clone();
            __tmp
        };
        {
            let __tmp = hxrt::array::Array::<crate::haxe_stack_item::StackItem>::new();
            self_.borrow_mut()._stack = __tmp.clone();
            __tmp
        };
        return self_;
    }

    pub fn get_message(self_: &crate::HxRefCell<ThreadPoolException>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return hxrt::string::HxString::from({
            let __b = __hx_this.borrow();
            __b._message.clone()
        });
    }

    pub fn get_stack(
        self_: &crate::HxRefCell<ThreadPoolException>,
    ) -> hxrt::array::Array<crate::haxe_stack_item::StackItem> {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._stack.clone()
        };
    }

    pub fn get_previous(
        self_: &crate::HxRefCell<ThreadPoolException>,
    ) -> Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>> {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._previous.clone()
        };
    }

    pub fn get_native(self_: &crate::HxRefCell<ThreadPoolException>) -> hxrt::dynamic::Dynamic {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._native.clone()
        };
    }

    fn unwrap(self_: &crate::HxRefCell<ThreadPoolException>) -> hxrt::dynamic::Dynamic {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._native.clone()
        };
    }

    pub fn to_string(self_: &crate::HxRefCell<ThreadPoolException>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return hxrt::string::HxString::from({
            let __b = __hx_this.borrow();
            __b._message.clone()
        });
    }

    pub fn details(self_: &crate::HxRefCell<ThreadPoolException>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::sys_thread_thread_pool_exception::ThreadPoolException> =
            self_.self_ref();
        return hxrt::string::HxString::from(hxrt::string::HxString::from(format!(
            "{}{}{}",
            "Exception: ",
            crate::sys_thread_thread_pool_exception::ThreadPoolException::to_string(&*__hx_this),
            crate::haxe_call_stack_call_stack_impl_::CallStackImpl::to_string(
                crate::sys_thread_thread_pool_exception::ThreadPoolException::get_stack(
                    &*__hx_this
                )
            )
        )));
    }
}

impl crate::haxe_exception::ExceptionTrait for crate::HxRefCell<ThreadPoolException> {
    fn __hx_get_u1_message(&self) -> hxrt::string::HxString {
        self.borrow()._message.clone()
    }
    fn __hx_set_u1_message(&self, v: hxrt::string::HxString) {
        self.borrow_mut()._message = v;
    }
    fn __hx_get_u1_previous(
        &self,
    ) -> Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>> {
        self.borrow()._previous.clone()
    }
    fn __hx_set_u1_previous(
        &self,
        v: Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>>,
    ) {
        self.borrow_mut()._previous = v;
    }
    fn __hx_get_u1_native(&self) -> hxrt::dynamic::Dynamic {
        self.borrow()._native.clone()
    }
    fn __hx_set_u1_native(&self, v: hxrt::dynamic::Dynamic) {
        self.borrow_mut()._native = v;
    }
    fn __hx_get_u1_stack(&self) -> hxrt::array::Array<crate::haxe_stack_item::StackItem> {
        self.borrow()._stack.clone()
    }
    fn __hx_set_u1_stack(&self, v: hxrt::array::Array<crate::haxe_stack_item::StackItem>) {
        self.borrow_mut()._stack = v;
    }
    fn details(&self) -> hxrt::string::HxString {
        ThreadPoolException::details(self)
    }
    fn get_message(&self) -> hxrt::string::HxString {
        ThreadPoolException::get_message(self)
    }
    fn get_native(&self) -> hxrt::dynamic::Dynamic {
        ThreadPoolException::get_native(self)
    }
    fn get_previous(
        &self,
    ) -> Option<crate::HxRc<dyn crate::haxe_exception::ExceptionTrait + Send + Sync>> {
        ThreadPoolException::get_previous(self)
    }
    fn get_stack(&self) -> hxrt::array::Array<crate::haxe_stack_item::StackItem> {
        ThreadPoolException::get_stack(self)
    }
    fn to_string(&self) -> hxrt::string::HxString {
        ThreadPoolException::to_string(self)
    }
    fn unwrap(&self) -> hxrt::dynamic::Dynamic {
        ThreadPoolException::unwrap(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::sys_thread_thread_pool_exception::__HX_TYPE_ID
    }
}
