// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xc9f41c03u32;

#[derive(Debug)]

pub struct Impl {}

impl Impl {
    pub fn new() -> crate::HxRef<crate::impl_::Impl> {
        let self_: crate::HxRef<crate::impl_::Impl> =
            std::rc::Rc::new(std::cell::RefCell::new(Impl {}));
        return self_;
    }

    pub fn say(_self_: &std::cell::RefCell<Impl>) -> String {
        return String::from("hi");
    }
}

impl crate::i_thing::IThing for std::cell::RefCell<Impl> {
    fn say(&self) -> String {
        Impl::say(self)
    }
}
