// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xc9f41c03u32;

#[derive(Debug)]

pub struct Impl {}

impl Impl {
    pub fn new() -> crate::HxRef<crate::impl_::Impl> {
        let self_: crate::HxRef<crate::impl_::Impl> = crate::HxRef::new(Impl {});
        return self_;
    }

    pub fn say(_self_: &crate::HxRefCell<Impl>) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(hxrt::string::HxString::from("hi"));
    }
}

impl crate::i_thing::IThing for crate::HxRefCell<Impl> {
    fn say(&self) -> hxrt::string::HxString {
        Impl::say(self)
    }
}
