// Generated by reflaxe.rust (POC)

use crate::HxRef;
use std::cell::RefCell;
use std::rc::Rc;

pub const __HX_TYPE_ID: u32 = 0xc9f41c03u32;

#[derive(Debug)]

pub struct Impl {}

impl Impl {
    pub fn new() -> HxRef<Impl> {
        let mut self_: HxRef<Impl> = Rc::new(RefCell::new(Impl {}));
        return self_;
    }

    pub fn say(self_: &RefCell<Impl>) -> String {
        return String::from("hi");
    }
}

impl crate::i_thing::IThing for RefCell<Impl> {
    fn say(&self) -> String {
        Impl::say(self)
    }
}
