// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod i_thing;
mod impl_;
mod sys;
use crate::i_thing::IThing;
use crate::impl_::Impl;
use crate::sys::Sys;

fn main() {
    let mut t: std::rc::Rc<dyn crate::i_thing::IThing> = Impl::new();
    println!("{}", t.say());
}
