// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn make_adder(k: i32) -> std::rc::Rc<dyn Fn(i32) -> i32> {
    return std::rc::Rc::new(move |x: i32| {
        return x + k;
    });
}

fn main() {
    let add10: std::rc::Rc<dyn Fn(i32) -> i32> =
        std::rc::Rc::new(move |a0: i32| make_adder(10)(a0));
    println!("{}", add10(1));
}
