// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod rust_borrow;
mod rust_slice_tools;
mod rust_str_tools;
mod rust_string_tools;
mod rust_vec_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let hay: String = String::from("hello");
    let needle: String = String::from("ell");
    {
        let h: &String = &hay;
        {
            let _hx_ref: &String = &needle;
            {
                let n: &str = _hx_ref;
                println!(
                    "{}",
                    hxrt::dynamic::from(crate::rust_string_tools::StringTools::contains(h, n))
                );
            }
        }
    }
    let mut v: Vec<i32> = Vec::<i32>::new();
    v.push(1);
    v.push(2);
    v.push(3);
    let mut sum: i32 = 0;
    {
        let mut _g: i32 = 0;
        let _g1: hxrt::array::Array<i32> = crate::rust_vec_tools::VecTools::to_array(v.clone());
        while _g < _g1.len() as i32 {
            let x: i32 = _g1.get_unchecked(_g as usize);
            {
                _g = _g + 1;
                _g
            };
            sum = sum + x;
        }
    }
    println!("{}", hxrt::dynamic::from(sum));
    println!(
        "{}",
        hxrt::dynamic::from(crate::rust_vec_tools::VecTools::len(&v))
    );
    {
        let vr: &Vec<i32> = &v;
        {
            let s: &[i32] = vr;
            let mut sum2: i32 = 0;
            {
                let mut _g_2: i32 = 0;
                let _g1_2: hxrt::array::Array<i32> =
                    crate::rust_slice_tools::SliceTools::to_array(s);
                while _g_2 < _g1_2.len() as i32 {
                    let x_2: i32 = _g1_2.get_unchecked(_g_2 as usize);
                    {
                        _g_2 = _g_2 + 1;
                        _g_2
                    };
                    sum2 = sum2 + x_2;
                }
            }
            println!("{}", hxrt::dynamic::from(sum2));
            println!(
                "{}",
                hxrt::dynamic::from(crate::rust_slice_tools::SliceTools::len(s))
            );
        }
    }
}
