// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x10deb5e1u32;

#[derive(Debug)]

pub struct StringTools {}

impl StringTools {
    pub fn contains(haystack: &String, needle: &str) -> bool {
        return haystack.contains(needle);
    }
}
