// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x3ed6a408u32;

#[derive(Debug)]

pub struct Int64Impl {}

impl Int64Impl {
    fn _new(
        x: crate::HxRef<crate::haxe_int64_int64::Int64>,
    ) -> crate::HxRef<crate::haxe_int64_int64::Int64> {
        let this1: crate::HxRef<crate::haxe_int64_int64::Int64>;
        this1 = x;
        return this1;
    }

    pub fn get_high(this1: crate::HxRef<crate::haxe_int64_int64::Int64>) -> i32 {
        return {
            let __b = this1.borrow();
            __b.high
        };
    }

    pub fn get_low(this1: crate::HxRef<crate::haxe_int64_int64::Int64>) -> i32 {
        return {
            let __b = this1.borrow();
            __b.low
        };
    }

    pub fn make(high: i32, low: i32) -> crate::HxRef<crate::haxe_int64_int64::Int64> {
        return {
            let x: crate::HxRef<crate::haxe_int64_int64::Int64> =
                crate::haxe_int64_int64::Int64::new(high, low);
            let this1: crate::HxRef<crate::haxe_int64_int64::Int64>;
            this1 = x;
            this1
        };
    }

    pub fn of_int(x: i32) -> crate::HxRef<crate::haxe_int64_int64::Int64> {
        return {
            let x_2: crate::HxRef<crate::haxe_int64_int64::Int64> =
                crate::haxe_int64_int64::Int64::new(x >> 31, x);
            let this1: crate::HxRef<crate::haxe_int64_int64::Int64>;
            this1 = x_2;
            this1
        };
    }

    pub fn copy(
        this1: crate::HxRef<crate::haxe_int64_int64::Int64>,
    ) -> crate::HxRef<crate::haxe_int64_int64::Int64> {
        return {
            let high: i32 = {
                let __b = this1.borrow();
                __b.high
            };
            let low: i32 = {
                let __b = this1.borrow();
                __b.low
            };
            {
                let x: crate::HxRef<crate::haxe_int64_int64::Int64> =
                    crate::haxe_int64_int64::Int64::new(high, low);
                let this1_2: crate::HxRef<crate::haxe_int64_int64::Int64>;
                this1_2 = x;
                this1_2
            }
        };
    }
}
