// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod rust_vec_tools;
mod sys;

fn main() {
    let a: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2]);
    let mut v: Vec<i32> = crate::rust_vec_tools::VecTools::from_array(a.clone());
    v.push(3);
    let a2: hxrt::array::Array<i32> = crate::rust_vec_tools::VecTools::to_array(v);
    crate::sys::Sys::println(hxrt::dynamic::from(a.len() as i32));
    crate::sys::Sys::println(hxrt::dynamic::from(a2.len() as i32));
    let b: hxrt::array::Array<i32> = a.clone();
    b.push(4);
    crate::sys::Sys::println(hxrt::dynamic::from(a.len() as i32));
    crate::sys::Sys::println(hxrt::dynamic::from(b.len() as i32));
    crate::sys::Sys::println(hxrt::dynamic::from(a2.len() as i32));
}
