// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod rust_borrow;
mod rust_hash_map_tools;
mod rust_option_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let mut m: std::collections::HashMap<String, i32> =
        std::collections::HashMap::<String, i32>::new();
    {
        let mm: &mut std::collections::HashMap<String, i32> = &mut m;
        {
            crate::rust_hash_map_tools::HashMapTools::insert(mm, String::from("a"), 1);
            crate::rust_hash_map_tools::HashMapTools::insert(mm, String::from("b"), 2);
        }
    }
    println!(
        "{}",
        hxrt::dynamic::from(crate::rust_hash_map_tools::HashMapTools::len(&m))
    );
    let key_a: String = String::from("a");
    {
        let k_a: &String = &key_a;
        {
            let mm_2: &mut std::collections::HashMap<String, i32> = &mut m;
            {
                let removed: Option<i32> =
                    crate::rust_hash_map_tools::HashMapTools::remove(mm_2, k_a);
                println!(
                    "{}",
                    hxrt::dynamic::from(match removed.clone() {
                        Option::Some(__p) => {
                            let _g: i32 = __p;
                            true
                        }
                        Option::None => false,
                    })
                );
            }
        }
    }
    println!(
        "{}",
        hxrt::dynamic::from(crate::rust_hash_map_tools::HashMapTools::len(&m))
    );
}
