// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x43dd80b3u32;

#[derive(Debug)]

pub struct Foo {
    pub x: i32,
}

impl Foo {
    pub fn new(x: i32) -> crate::HxRef<crate::foo::Foo> {
        let self_: crate::HxRef<crate::foo::Foo> =
            crate::HxRc::new(crate::HxRefCell::new(Foo { x: x }));
        return self_;
    }
}
