// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod foo;
mod sys;

fn main() {
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string primitives ---"))
    );
    println!("{}", hxrt::dynamic::from(String::from("1")));
    println!("{}", hxrt::dynamic::from(String::from("true")));
    println!("{}", hxrt::dynamic::from(1.5.to_string().clone()));
    println!("{}", hxrt::dynamic::from(String::from("hi")));
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string array ---"))
    );
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3]);
    println!(
        "{}",
        hxrt::dynamic::from(hxrt::dynamic::from(xs.clone()).to_haxe_string().clone())
    );
    println!("{}", hxrt::dynamic::from(xs.toString().clone()));
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string object ---"))
    );
    let foo: crate::HxRef<crate::foo::Foo> = crate::foo::Foo::new(3);
    println!(
        "{}",
        hxrt::dynamic::from(hxrt::dynamic::from(foo.clone()).to_haxe_string().clone())
    );
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Sys.println Dynamic ---"))
    );
    crate::sys::Sys::println(hxrt::dynamic::from(foo.clone()));
    let mut n: Option<i32> = None;
    crate::sys::Sys::println(hxrt::dynamic::from(n));
    {
        let __tmp = 5;
        n = Some(__tmp);
        __tmp
    };
    crate::sys::Sys::println(hxrt::dynamic::from(n));
}
