// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod foo;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string primitives ---"))
    );
    println!("{}", hxrt::dynamic::from(String::from("1")));
    println!("{}", hxrt::dynamic::from(String::from("true")));
    println!("{}", hxrt::dynamic::from(1.5.to_string().clone()));
    println!("{}", hxrt::dynamic::from(String::from("hi")));
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string array ---"))
    );
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3]);
    println!(
        "{}",
        hxrt::dynamic::from(hxrt::dynamic::from(xs.clone()).to_haxe_string().clone())
    );
    println!("{}", hxrt::dynamic::from(xs.toString().clone()));
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Std.string object ---"))
    );
    let foo: crate::HxRef<crate::foo::Foo> = crate::foo::Foo::new(3);
    println!(
        "{}",
        hxrt::dynamic::from(hxrt::dynamic::from(foo.clone()).to_haxe_string().clone())
    );
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- Sys.println Dynamic ---"))
    );
    crate::sys::Sys::println(hxrt::dynamic::from(foo.clone()));
    let mut n: Option<i32> = None;
    crate::sys::Sys::println(hxrt::dynamic::from(n));
    {
        let __tmp = 5;
        n = Some(__tmp);
        __tmp
    };
    crate::sys::Sys::println(hxrt::dynamic::from(n));
}
