// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x0672f642u32;

#[derive(Debug)]

pub struct MutSliceTools {}

impl MutSliceTools {
    pub fn len<T>(s: &mut [T]) -> i32 {
        return s.len() as i32;
    }

    pub fn get<T>(s: &mut [T], index: i32) -> Option<&T> {
        return s.get(index as usize);
    }

    pub fn set<T>(s: &mut [T], index: i32, value: T) {
        s[index as usize] = value;
    }
}
