// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x6cc99212u32;

#[derive(Debug)]

pub struct HashMapTools {}

impl HashMapTools {
    pub fn get_cloned<K: Eq + std::hash::Hash + Clone, V: Clone>(
        m: &std::collections::HashMap<K, V>,
        key: &K,
    ) -> Option<V> {
        return m.get(key).cloned();
    }

    pub fn len<K, V>(m: &std::collections::HashMap<K, V>) -> i32 {
        return m.len() as i32;
    }

    pub fn insert<K: Eq + std::hash::Hash, V>(
        m: &mut std::collections::HashMap<K, V>,
        key: K,
        value: V,
    ) -> Option<V> {
        return m.insert(key, value);
    }

    pub fn remove<K: Eq + std::hash::Hash, V>(
        m: &mut std::collections::HashMap<K, V>,
        key: &K,
    ) -> Option<V> {
        return m.remove(key);
    }

    pub fn remove_exists<K: Eq + std::hash::Hash, V>(
        m: &mut std::collections::HashMap<K, V>,
        key: &K,
    ) -> bool {
        return m.remove(key).is_some();
    }

    pub fn keys_owned<K: Eq + std::hash::Hash + Clone, V>(
        m: &std::collections::HashMap<K, V>,
    ) -> hxrt::iter::Iter<K> {
        return hxrt::iter::Iter::from_vec(m.keys().cloned().collect::<Vec<_>>());
    }

    pub fn values_owned<K: Eq + std::hash::Hash, V: Clone>(
        m: &std::collections::HashMap<K, V>,
    ) -> hxrt::iter::Iter<V> {
        return hxrt::iter::Iter::from_vec(m.values().cloned().collect::<Vec<_>>());
    }

    pub fn key_values_owned<K: Eq + std::hash::Hash + Clone, V: Clone>(
        m: &std::collections::HashMap<K, V>,
    ) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>> {
        return hxrt::iter::Iter::from_vec(
            m.iter()
                .map(|(k, v)| hxrt::iter::KeyValue {
                    key: k.clone(),
                    value: v.clone(),
                })
                .collect::<Vec<_>>(),
        );
    }

    pub fn debug_string<K: Eq + std::hash::Hash + std::fmt::Debug, V: std::fmt::Debug>(
        m: &std::collections::HashMap<K, V>,
    ) -> String {
        return format!("{:?}", m);
    }
}
