// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x0a67ae35u32;

#[derive(Debug)]

pub struct StringKeyValueIterator {
    offset: i32,
    s: String,
}

impl StringKeyValueIterator {
    pub fn new(
        s: String,
    ) -> crate::HxRef<crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator> {
        let self_: crate::HxRef<
            crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator,
        > = crate::HxRef::new(StringKeyValueIterator { offset: 0, s: s });
        return self_;
    }

    pub fn has_next(self_: &crate::HxRefCell<StringKeyValueIterator>) -> bool {
        let __hx_this: crate::HxRef<
            crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator,
        > = self_.self_ref();
        return ({
            let __b = __hx_this.borrow();
            __b.offset
        }) < hxrt::string::len(
            ({
                let __b = __hx_this.borrow();
                __b.s.clone()
            })
            .as_str(),
        );
    }

    pub fn next(
        self_: &crate::HxRefCell<StringKeyValueIterator>,
    ) -> crate::HxRef<hxrt::anon::Anon> {
        let __hx_this: crate::HxRef<
            crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator,
        > = self_.self_ref();
        return {
            let __o = crate::HxRef::new(hxrt::anon::Anon::new());
            {
                let mut __b = __o.borrow_mut();
                __b.set("key", {
                    let __b = __hx_this.borrow();
                    __b.offset
                });
                __b.set(
                    "value",
                    crate::string_tools::StringTools::fast_code_at(
                        {
                            let __b = __hx_this.borrow();
                            __b.s.clone()
                        },
                        {
                            let __tmp = self_.borrow().offset;
                            self_.borrow_mut().offset = __tmp + 1;
                            __tmp
                        },
                    ),
                );
            };
            __o
        };
    }
}
