// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x0672f642u32;

#[derive(Debug)]

pub struct MutSliceTools {}

impl MutSliceTools {
    pub fn len<T>(s: &mut [T]) -> i32 {
        return crate::mut_slice_tools::MutSliceTools::len(s);
    }

    pub fn get<T>(s: &mut [T], index: i32) -> Option<&T> {
        return crate::mut_slice_tools::MutSliceTools::get(s, index);
    }

    pub fn set<T>(s: &mut [T], index: i32, value: T) {
        crate::mut_slice_tools::MutSliceTools::set(s, index, value);
    }
}
