// Generated by reflaxe.rust (POC)

use crate::HxRef;
use std::cell::RefCell;
use std::rc::Rc;

pub struct Foo {
    pub x: i32,
}

impl Foo {
    pub fn new(x: i32) -> HxRef<Foo> {
        let mut self_: HxRef<Foo> = Rc::new(RefCell::new(Foo { x: 0 }));
        {
            let __tmp = x;
            self_.borrow_mut().x = __tmp.clone();
            __tmp
        };
        return self_;
    }

    pub fn inc(self_: &HxRef<Foo>) {
        {
            let __tmp = (self_.borrow().x + 1);
            self_.borrow_mut().x = __tmp.clone();
            __tmp
        };
    }

    pub fn getX(self_: &HxRef<Foo>) -> i32 {
        return self_.borrow().x;
    }
}
