// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x6362faa0u32;

#[derive(Debug)]
pub struct OptionalPrimitiveDefaults {
    pub flag: bool,
    pub count: i32,
    pub name: String,
}

impl OptionalPrimitiveDefaults {
    pub fn new(
        flag: Option<bool>,
        count: Option<i32>,
        name: Option<String>,
    ) -> crate::HxRef<crate::optional_primitive_defaults::OptionalPrimitiveDefaults> {
        let self_: crate::HxRef<crate::optional_primitive_defaults::OptionalPrimitiveDefaults> =
            crate::HxRef::new(OptionalPrimitiveDefaults {
                flag: {
                    let __hx_opt = flag;
                    match __hx_opt {
                        Some(__v) => __v,
                        None => {
                            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
                        }
                    }
                },
                count: {
                    let __hx_opt = count;
                    match __hx_opt {
                        Some(__v) => __v,
                        None => {
                            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
                        }
                    }
                },
                name: {
                    let __hx_opt = name.clone();
                    match &__hx_opt {
                        Some(__v) => __v.clone(),
                        None => {
                            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
                        }
                    }
                },
            });
        return self_;
    }

    pub fn describe(self_: &crate::HxRefCell<OptionalPrimitiveDefaults>) -> String {
        let __hx_this: crate::HxRef<crate::optional_primitive_defaults::OptionalPrimitiveDefaults> =
            self_.self_ref();
        return format!(
            "{}{}{}{}{}",
            if {
                let __b = __hx_this.borrow();
                __b.flag
            } {
                String::from("yes")
            } else {
                String::from("no")
            },
            ":",
            hxrt::dynamic::from({
                let __b = __hx_this.borrow();
                __b.count
            })
            .to_haxe_string(),
            ":",
            &__hx_this.borrow().name
        );
    }
}
