// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn main() {
    let a: i32 = 7;
    let b: i32 = 3;
    crate::sys::Sys::println(hxrt::dynamic::from(a % b));
    crate::sys::Sys::println(hxrt::dynamic::from(a & b));
    crate::sys::Sys::println(hxrt::dynamic::from(a | b));
    crate::sys::Sys::println(hxrt::dynamic::from(a ^ b));
    crate::sys::Sys::println(hxrt::dynamic::from(a << 2));
    crate::sys::Sys::println(hxrt::dynamic::from(a >> 1));
    crate::sys::Sys::println(hxrt::dynamic::from((a as u32 >> 1 as u32) as i32));
    crate::sys::Sys::println(hxrt::dynamic::from(!a));
    let mut c: i32 = 1;
    {
        c = c + 2;
        c
    };
    {
        c = c % 2;
        c
    };
    {
        c = c | 4;
        c
    };
    {
        c = c & 7;
        c
    };
    {
        c = c ^ 3;
        c
    };
    {
        c = c << 1;
        c
    };
    {
        c = c >> 1;
        c
    };
    crate::sys::Sys::println(hxrt::dynamic::from(c));
}
