// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xfddc42d8u32;

#[derive(Debug)]
pub struct Channel {}

impl Channel {
    pub fn new() -> crate::HxRef<crate::channel::Channel> {
        let self_: crate::HxRef<crate::channel::Channel> = crate::HxRef::new(Channel {});
        return self_;
    }

    pub fn label(_self_: &crate::HxRefCell<Channel>) -> String {
        return String::from("ready");
    }
}

impl crate::i_channel::IChannel for crate::HxRefCell<Channel> {
    fn label(&self) -> String {
        Channel::label(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::channel::__HX_TYPE_ID
    }
}
