// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x1643276fu32;

pub struct ChannelOwner {
    channel: crate::HxDynRef<dyn crate::i_channel::IChannel + Send + Sync>,
}

impl ChannelOwner {
    pub fn new(
        channel: crate::HxDynRef<dyn crate::i_channel::IChannel + Send + Sync>,
    ) -> crate::HxRef<crate::channel_owner::ChannelOwner> {
        let self_: crate::HxRef<crate::channel_owner::ChannelOwner> =
            crate::HxRef::new(ChannelOwner { channel: channel });
        return self_;
    }

    pub fn label(self_: &crate::HxRefCell<ChannelOwner>) -> String {
        let __hx_this: crate::HxRef<crate::channel_owner::ChannelOwner> = self_.self_ref();
        return if ({
            let __b = __hx_this.borrow();
            __b.channel.clone()
        })
        .is_null()
        {
            String::from("missing")
        } else {
            ({
                let __b = __hx_this.borrow();
                __b.channel.clone()
            })
            .label()
        };
    }
}
