// Generated by reflaxe.rust

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod fp_helper;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int32_int32_impl_;
mod haxe_int64_helper;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_json;
mod haxe_json_value;
mod haxe_stack_item;
mod int32_tools;
mod map_storage_tools_nullable;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => matches!(expected, 0x44f4c432u32),
        0x39e0cd5bu32 => matches!(expected, 0x44f4c432u32),
        0xd7e07825u32 => matches!(expected, 0x44f4c432u32),
        0x181f937bu32 => matches!(expected, 0x44f4c432u32),
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        _ => false,
    }
}

fn object_fields(
    value: crate::haxe_json_value::Value,
) -> hxrt::array::Array<crate::HxRef<hxrt::anon::Anon>> {
    return if (match value.clone() {
        crate::haxe_json_value::Value::JString(__p) => 3,
        crate::haxe_json_value::Value::JObject(__p0, __p1) => 4,
        crate::haxe_json_value::Value::JNumber(__p) => 2,
        crate::haxe_json_value::Value::JNull => 0,
        crate::haxe_json_value::Value::JBool(__p) => 1,
        crate::haxe_json_value::Value::JArray(__p) => 5,
    }) == 4
    {
        let _g: hxrt::array::Array<hxrt::string::HxString> = match value.clone() {
            crate::haxe_json_value::Value::JObject(__p, _) => __p,
            _ => unreachable!(),
        };
        let _g1: hxrt::array::Array<crate::haxe_json_value::Value> = match value {
            crate::haxe_json_value::Value::JObject(_, __p) => __p,
            _ => unreachable!(),
        };
        {
            let keys: hxrt::array::Array<hxrt::string::HxString> = _g;
            let values: hxrt::array::Array<crate::haxe_json_value::Value> = _g1;
            {
                let out: hxrt::array::Array<crate::HxRef<hxrt::anon::Anon>> =
                    hxrt::array::Array::<crate::HxRef<hxrt::anon::Anon>>::new();
                let mut i: i32 = 0;
                while i < (keys.len() as i32) {
                    out.push({
                        let __o = crate::HxRef::new(hxrt::anon::Anon::new());
                        {
                            let mut __b = __o.borrow_mut();
                            __b.set("name", keys.get_unchecked(i as usize));
                            __b.set("value", values.get_unchecked(i as usize));
                        };
                        __o
                    });
                    i = i + 1;
                }
                out
            }
        }
    } else {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "expected object",
        )));
    };
}

fn read_optional_field(
    fields: hxrt::array::Array<crate::HxRef<hxrt::anon::Anon>>,
    name: hxrt::string::HxString,
) -> Option<crate::haxe_json_value::Value> {
    for field in fields.iter_borrowed() {
        if field.borrow().get::<hxrt::string::HxString>("name") == name {
            return Some(field.borrow().get::<crate::haxe_json_value::Value>("value"));
        }
    }
    return None;
}

fn describe_optional_field(
    fields: hxrt::array::Array<crate::HxRef<hxrt::anon::Anon>>,
    name: hxrt::string::HxString,
) -> hxrt::string::HxString {
    {
        let _g: Option<crate::haxe_json_value::Value> =
            read_optional_field(fields.clone(), hxrt::string::HxString::from(name));
        return hxrt::string::HxString::from(if _g.is_none() {
            hxrt::string::HxString::from(hxrt::string::HxString::from("missing"))
        } else {
            hxrt::string::HxString::from(match _g.clone() {
                Some(crate::haxe_json_value::Value::JNull) => {
                    hxrt::string::HxString::from(hxrt::string::HxString::from("json-null"))
                }
                Some(crate::haxe_json_value::Value::JBool(__p)) => {
                    let _g_2: bool = __p;
                    hxrt::string::HxString::from({
                        let value: bool = _g_2;
                        hxrt::string::HxString::from(format!("{}{}", "bool:", value.to_string()))
                    })
                }
                Some(crate::haxe_json_value::Value::JNumber(__p)) => {
                    let _g_3: f64 = __p;
                    hxrt::string::HxString::from({
                        let value_2: f64 = _g_3;
                        hxrt::string::HxString::from(format!(
                            "{}{}",
                            "number:",
                            value_2.to_string()
                        ))
                    })
                }
                Some(crate::haxe_json_value::Value::JString(__p)) => {
                    let _g_4: hxrt::string::HxString = hxrt::string::HxString::from(__p);
                    hxrt::string::HxString::from({
                        let value_3: hxrt::string::HxString = hxrt::string::HxString::from(_g_4);
                        hxrt::string::HxString::from(format!("{}{}", "string:", &value_3))
                    })
                }
                _ => hxrt::string::HxString::from(hxrt::string::HxString::from("other")),
            })
        });
    }
}

fn main() {
    let fields: hxrt::array::Array<crate::HxRef<hxrt::anon::Anon>> = object_fields(crate::haxe_json::Json::parse_value(hxrt::string::HxString::from(hxrt::string::HxString::from("{\"name\":\"Ada\",\"score\":4.5,\"enabled\":true,\"tags\":[\"haxe\"],\"empty\":null}"))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "name=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("name"))
        )
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "score=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("score"))
        )
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "enabled=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("enabled"))
        )
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "tags=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("tags"))
        )
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "empty=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("empty"))
        )
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "missing=",
        describe_optional_field(
            fields.clone(),
            hxrt::string::HxString::from(hxrt::string::HxString::from("missing"))
        )
    ))));
}
