// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x70f28bdfu32;

#[derive(Debug)]

pub struct StringTools {}

impl StringTools {
    pub fn url_encode(s: hxrt::string::HxString) -> hxrt::string::HxString {
        let bytes: crate::HxRef<hxrt::bytes::Bytes> =
            crate::HxRef::new(hxrt::bytes::Bytes::of_string(s.as_str()));
        let out: crate::HxRef<crate::string_buf::StringBuf> = crate::string_buf::StringBuf::new();
        {
            let mut _g: i32 = 0;
            let _g1: i32 = bytes.borrow().length();
            while _g < _g1 {
                let i: i32 = {
                    let __next = _g + 1;
                    std::mem::replace(&mut _g, __next)
                };
                let b: i32 = bytes.borrow().get(i);
                let is_unreserved: bool = b >= 65 && b <= 90
                    || b >= 97 && b <= 122
                    || b >= 48 && b <= 57
                    || b == 45
                    || b == 95
                    || b == 46
                    || b == 126;
                if is_unreserved {
                    crate::string_buf::StringBuf::add_char(&*out, b);
                } else {
                    if b == 32 {
                        crate::string_buf::StringBuf::add(
                            &*out,
                            hxrt::dynamic::from(hxrt::string::HxString::from("%20")),
                        );
                    } else {
                        crate::string_buf::StringBuf::add(
                            &*out,
                            hxrt::dynamic::from(hxrt::string::HxString::from("%")),
                        );
                        crate::string_buf::StringBuf::add(
                            &*out,
                            hxrt::dynamic::from(crate::string_tools::StringTools::hex(b, Some(2))),
                        );
                    }
                }
            }
        }
        return hxrt::string::HxString::from(crate::string_buf::StringBuf::to_string(&*out));
    }

    pub fn url_decode(s: hxrt::string::HxString) -> hxrt::string::HxString {
        let input: hxrt::string::HxString =
            hxrt::string::HxString::from(crate::string_tools::StringTools::replace(
                hxrt::string::HxString::from(s),
                hxrt::string::HxString::from(hxrt::string::HxString::from("+")),
                hxrt::string::HxString::from(hxrt::string::HxString::from(" ")),
            ));
        let bytes: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::new();
        let mut i: i32 = 0;
        while i < hxrt::string::len(input.as_str()) {
            let c: hxrt::string::HxString = hxrt::string::HxString::from(
                hxrt::string::HxString::from(hxrt::string::substr(input.as_str(), i, Some(1))),
            );
            if c == hxrt::string::HxString::from("%") && i + 2 < hxrt::string::len(input.as_str()) {
                let hi: i32 = {
                    let ch: hxrt::string::HxString =
                        hxrt::string::HxString::from(hxrt::string::HxString::from(
                            hxrt::string::substr(input.as_str(), i + 1, Some(1)),
                        ));
                    if ch == hxrt::string::HxString::from("0") {
                        0
                    } else {
                        if ch == hxrt::string::HxString::from("1") {
                            1
                        } else {
                            if ch == hxrt::string::HxString::from("2") {
                                2
                            } else {
                                if ch == hxrt::string::HxString::from("3") {
                                    3
                                } else {
                                    if ch == hxrt::string::HxString::from("4") {
                                        4
                                    } else {
                                        if ch == hxrt::string::HxString::from("5") {
                                            5
                                        } else {
                                            if ch == hxrt::string::HxString::from("6") {
                                                6
                                            } else {
                                                if ch == hxrt::string::HxString::from("7") {
                                                    7
                                                } else {
                                                    if ch == hxrt::string::HxString::from("8") {
                                                        8
                                                    } else {
                                                        if ch == hxrt::string::HxString::from("9") {
                                                            9
                                                        } else {
                                                            if ch
                                                                == hxrt::string::HxString::from("a")
                                                                || ch
                                                                    == hxrt::string::HxString::from(
                                                                        "A",
                                                                    )
                                                            {
                                                                10
                                                            } else {
                                                                if ch == hxrt::string::HxString::from("b") || ch == hxrt::string::HxString::from("B") { 11 } else { if ch == hxrt::string::HxString::from("c") || ch == hxrt::string::HxString::from("C") { 12 } else { if ch == hxrt::string::HxString::from("d") || ch == hxrt::string::HxString::from("D") { 13 } else { if ch == hxrt::string::HxString::from("e") || ch == hxrt::string::HxString::from("E") { 14 } else { if ch == hxrt::string::HxString::from("f") || ch == hxrt::string::HxString::from("F") { 15 } else { -1 } } } } }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                };
                let lo: i32 = {
                    let ch_2: hxrt::string::HxString =
                        hxrt::string::HxString::from(hxrt::string::HxString::from(
                            hxrt::string::substr(input.as_str(), i + 2, Some(1)),
                        ));
                    if ch_2 == hxrt::string::HxString::from("0") {
                        0
                    } else {
                        if ch_2 == hxrt::string::HxString::from("1") {
                            1
                        } else {
                            if ch_2 == hxrt::string::HxString::from("2") {
                                2
                            } else {
                                if ch_2 == hxrt::string::HxString::from("3") {
                                    3
                                } else {
                                    if ch_2 == hxrt::string::HxString::from("4") {
                                        4
                                    } else {
                                        if ch_2 == hxrt::string::HxString::from("5") {
                                            5
                                        } else {
                                            if ch_2 == hxrt::string::HxString::from("6") {
                                                6
                                            } else {
                                                if ch_2 == hxrt::string::HxString::from("7") {
                                                    7
                                                } else {
                                                    if ch_2 == hxrt::string::HxString::from("8") {
                                                        8
                                                    } else {
                                                        if ch_2 == hxrt::string::HxString::from("9")
                                                        {
                                                            9
                                                        } else {
                                                            if ch_2
                                                                == hxrt::string::HxString::from("a")
                                                                || ch_2
                                                                    == hxrt::string::HxString::from(
                                                                        "A",
                                                                    )
                                                            {
                                                                10
                                                            } else {
                                                                if ch_2 == hxrt::string::HxString::from("b") || ch_2 == hxrt::string::HxString::from("B") { 11 } else { if ch_2 == hxrt::string::HxString::from("c") || ch_2 == hxrt::string::HxString::from("C") { 12 } else { if ch_2 == hxrt::string::HxString::from("d") || ch_2 == hxrt::string::HxString::from("D") { 13 } else { if ch_2 == hxrt::string::HxString::from("e") || ch_2 == hxrt::string::HxString::from("E") { 14 } else { if ch_2 == hxrt::string::HxString::from("f") || ch_2 == hxrt::string::HxString::from("F") { 15 } else { -1 } } } } }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                };
                if hi >= 0 && lo >= 0 {
                    bytes.push(hi << 4 | lo);
                    {
                        i = i + 3;
                        i
                    };
                    continue;
                }
            }
            let chunk: crate::HxRef<hxrt::bytes::Bytes> =
                crate::HxRef::new(hxrt::bytes::Bytes::of_string(
                    hxrt::string::HxString::from(hxrt::string::char_at(input.as_str(), i)).as_str(),
                ));
            {
                let mut _g: i32 = 0;
                let _g1: i32 = chunk.borrow().length();
                while _g < _g1 {
                    let j: i32 = {
                        let __next = _g + 1;
                        std::mem::replace(&mut _g, __next)
                    };
                    bytes.push(chunk.borrow().get(j));
                }
            }
            i = i + 1;
        }
        let out: crate::HxRef<hxrt::bytes::Bytes> =
            crate::HxRef::new(hxrt::bytes::Bytes::alloc(bytes.len() as i32 as usize));
        {
            let mut _g_2: i32 = 0;
            let _g1_2: i32 = bytes.len() as i32;
            while _g_2 < _g1_2 {
                let index: i32 = {
                    let __next = _g_2 + 1;
                    std::mem::replace(&mut _g_2, __next)
                };
                out.borrow_mut()
                    .set(index, bytes.get_unchecked(index as usize));
            }
        }
        return hxrt::string::HxString::from(out.borrow().to_string());
    }

    pub fn contains(s: hxrt::string::HxString, value: hxrt::string::HxString) -> bool {
        return hxrt::string::index_of(
            s.as_str(),
            hxrt::string::HxString::from(value).as_str(),
            None,
        ) != -1;
    }

    pub fn starts_with(s: hxrt::string::HxString, start: hxrt::string::HxString) -> bool {
        return hxrt::string::len(s.as_str()) >= hxrt::string::len(start.as_str())
            && hxrt::string::index_of(
                s.as_str(),
                hxrt::string::HxString::from(start.clone()).as_str(),
                Some(0),
            ) == 0;
    }

    pub fn ends_with(s: hxrt::string::HxString, end: hxrt::string::HxString) -> bool {
        let elen: i32 = hxrt::string::len(end.as_str());
        let slen: i32 = hxrt::string::len(s.as_str());
        return slen >= elen
            && hxrt::string::index_of(
                s.as_str(),
                hxrt::string::HxString::from(end.clone()).as_str(),
                Some(slen - elen),
            ) == slen - elen;
    }

    pub fn is_space(s: hxrt::string::HxString, pos: i32) -> bool {
        if hxrt::string::len(s.as_str()) == 0 || pos < 0 || pos >= hxrt::string::len(s.as_str()) {
            return false;
        }
        let c: i32 = crate::string_tools::StringTools::fast_code_at(
            hxrt::string::HxString::from(s.clone()),
            pos,
        );
        return c > 8 && c < 14 || c == 32;
    }

    pub fn ltrim(s: hxrt::string::HxString) -> hxrt::string::HxString {
        let l: i32 = hxrt::string::len(s.as_str());
        let mut r: i32 = 0;
        while r < l
            && crate::string_tools::StringTools::is_space(
                hxrt::string::HxString::from(s.clone()),
                r,
            )
        {
            r = r + 1;
        }
        return hxrt::string::HxString::from(if r > 0 {
            hxrt::string::HxString::from(hxrt::string::substr(s.as_str(), r, Some(l - r)))
        } else {
            s
        });
    }

    pub fn rtrim(s: hxrt::string::HxString) -> hxrt::string::HxString {
        let l: i32 = hxrt::string::len(s.as_str());
        let mut r: i32 = 0;
        while r < l
            && crate::string_tools::StringTools::is_space(
                hxrt::string::HxString::from(s.clone()),
                l - r - 1,
            )
        {
            r = r + 1;
        }
        return hxrt::string::HxString::from(if r > 0 {
            hxrt::string::HxString::from(hxrt::string::substr(s.as_str(), 0, Some(l - r)))
        } else {
            s
        });
    }

    pub fn trim(s: hxrt::string::HxString) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(crate::string_tools::StringTools::ltrim(
            hxrt::string::HxString::from(crate::string_tools::StringTools::rtrim(
                hxrt::string::HxString::from(s),
            )),
        ));
    }

    pub fn lpad(
        s: hxrt::string::HxString,
        c: hxrt::string::HxString,
        l: i32,
    ) -> hxrt::string::HxString {
        if hxrt::string::len(c.as_str()) <= 0 {
            return hxrt::string::HxString::from(s);
        }
        let pad_len: i32 = l - hxrt::string::len(s.as_str());
        if pad_len <= 0 {
            return hxrt::string::HxString::from(s);
        }
        let mut buf: hxrt::string::HxString =
            hxrt::string::HxString::from(hxrt::string::HxString::from(""));
        while hxrt::string::len(buf.as_str()) < pad_len {
            {
                let __tmp = c.clone();
                buf = hxrt::string::HxString::from(format!("{}{}", buf, __tmp));
            }
        }
        return hxrt::string::HxString::from(hxrt::string::HxString::from(format!(
            "{}{}",
            &buf, &s
        )));
    }

    pub fn rpad(
        s: hxrt::string::HxString,
        c: hxrt::string::HxString,
        l: i32,
    ) -> hxrt::string::HxString {
        if hxrt::string::len(c.as_str()) <= 0 {
            return hxrt::string::HxString::from(s);
        }
        if l <= hxrt::string::len(s.as_str()) {
            return hxrt::string::HxString::from(s);
        }
        let mut out: hxrt::string::HxString = hxrt::string::HxString::from(s.clone());
        while hxrt::string::len(out.as_str()) < l {
            {
                let __tmp = c.clone();
                out = hxrt::string::HxString::from(format!("{}{}", out, __tmp));
            }
        }
        return hxrt::string::HxString::from(out);
    }

    pub fn replace(
        s: hxrt::string::HxString,
        sub: hxrt::string::HxString,
        by: hxrt::string::HxString,
    ) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(hxrt::string::HxString::from(
            hxrt::string::split_hx(s.as_str(), hxrt::string::HxString::from(sub).as_str())
                .join(hxrt::string::HxString::from(by)),
        ));
    }

    pub fn hex(n: i32, digits: Option<i32>) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(hxrt::string::hex_upper(n, digits));
    }

    pub fn fast_code_at(s: hxrt::string::HxString, index: i32) -> i32 {
        return hxrt::string::fast_code_at_or_eof(hxrt::string::HxString::from(s), index);
    }

    fn hex_digit_value(ch: hxrt::string::HxString) -> i32 {
        return if ch == hxrt::string::HxString::from("0") {
            0
        } else {
            if ch == hxrt::string::HxString::from("1") {
                1
            } else {
                if ch == hxrt::string::HxString::from("2") {
                    2
                } else {
                    if ch == hxrt::string::HxString::from("3") {
                        3
                    } else {
                        if ch == hxrt::string::HxString::from("4") {
                            4
                        } else {
                            if ch == hxrt::string::HxString::from("5") {
                                5
                            } else {
                                if ch == hxrt::string::HxString::from("6") {
                                    6
                                } else {
                                    if ch == hxrt::string::HxString::from("7") {
                                        7
                                    } else {
                                        if ch == hxrt::string::HxString::from("8") {
                                            8
                                        } else {
                                            if ch == hxrt::string::HxString::from("9") {
                                                9
                                            } else {
                                                if ch == hxrt::string::HxString::from("a")
                                                    || ch == hxrt::string::HxString::from("A")
                                                {
                                                    10
                                                } else {
                                                    if ch == hxrt::string::HxString::from("b")
                                                        || ch == hxrt::string::HxString::from("B")
                                                    {
                                                        11
                                                    } else {
                                                        if ch == hxrt::string::HxString::from("c")
                                                            || ch
                                                                == hxrt::string::HxString::from("C")
                                                        {
                                                            12
                                                        } else {
                                                            if ch
                                                                == hxrt::string::HxString::from("d")
                                                                || ch
                                                                    == hxrt::string::HxString::from(
                                                                        "D",
                                                                    )
                                                            {
                                                                13
                                                            } else {
                                                                if ch == hxrt::string::HxString::from("e") || ch == hxrt::string::HxString::from("E") { 14 } else { if ch == hxrt::string::HxString::from("f") || ch == hxrt::string::HxString::from("F") { 15 } else { -1 } }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        };
    }

    pub fn unsafe_code_at(s: hxrt::string::HxString, index: i32) -> i32 {
        return crate::string_tools::StringTools::fast_code_at(
            hxrt::string::HxString::from(s),
            index,
        );
    }

    pub fn is_eof(c: i32) -> bool {
        return c == -1;
    }

    pub fn iterator(
        s: hxrt::string::HxString,
    ) -> crate::HxRef<crate::haxe_iterators_string_iterator::StringIterator> {
        return crate::haxe_iterators_string_iterator::StringIterator::new(
            hxrt::string::HxString::from(s),
        );
    }

    pub fn key_value_iterator(
        s: hxrt::string::HxString,
    ) -> crate::HxRef<crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator> {
        return crate::haxe_iterators_string_key_value_iterator::StringKeyValueIterator::new(
            hxrt::string::HxString::from(s),
        );
    }

    fn utf16_code_point_at(s: hxrt::string::HxString, index: i32) -> i32 {
        let mut c: i32 = crate::string_tools::StringTools::fast_code_at(
            hxrt::string::HxString::from(s.clone()),
            index,
        );
        if c >= 55296 && c <= 56319 {
            c = c - 55232 << 10
                | crate::string_tools::StringTools::fast_code_at(
                    hxrt::string::HxString::from(s.clone()),
                    index + 1,
                ) & 1023;
        }
        return c;
    }
}
