// Generated by reflaxe.rust (POC)

// Haxe interface -> Rust trait

pub trait Connection: Send + Sync {
    fn request(
        &self,
        s: String,
    ) -> crate::HxRc<dyn crate::sys_db_result_set::ResultSet + Send + Sync>;
    fn close(&self) -> ();
    fn escape(&self, s: String) -> String;
    fn quote(&self, s: String) -> String;
    fn add_value(
        &self,
        s: crate::HxRef<crate::string_buf::StringBuf>,
        v: hxrt::dynamic::Dynamic,
    ) -> ();
    fn last_insert_id(&self) -> i32;
    fn db_name(&self) -> String;
    fn start_transaction(&self) -> ();
    fn commit(&self) -> ();
    fn rollback(&self) -> ();
}
