// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x792eeae2u32;

#[derive(Debug)]

pub struct Mysql {}

impl Mysql {
    pub fn connect(
        params: crate::HxRef<hxrt::anon::Anon>,
    ) -> crate::HxRc<dyn crate::sys_db_connection::Connection + Send + Sync> {
        return crate::sys_db_mysql_mysql_connection::MysqlConnection::new(params.clone());
    }
}
