// Generated by reflaxe.rust

static __HX_STATIC_MUTEX: std::sync::OnceLock<
    hxrt::cell::HxCell<crate::HxRef<crate::sys_thread_mutex::Mutex>>,
> = std::sync::OnceLock::new();
fn __hx_static_cell_mutex(
) -> &'static hxrt::cell::HxCell<crate::HxRef<crate::sys_thread_mutex::Mutex>> {
    __HX_STATIC_MUTEX.get_or_init(|| hxrt::cell::HxCell::new(crate::sys_thread_mutex::Mutex::new()))
}
pub(crate) fn __hx_static_get_mutex() -> crate::HxRef<crate::sys_thread_mutex::Mutex> {
    __hx_static_cell_mutex().borrow().clone()
}
pub(crate) fn __hx_static_set_mutex(value: crate::HxRef<crate::sys_thread_mutex::Mutex>) {
    *__hx_static_cell_mutex().borrow_mut() = value;
}

static __HX_STATIC_SLEEP_LOCK: std::sync::OnceLock<
    hxrt::cell::HxCell<crate::HxRef<crate::sys_thread_lock::Lock>>,
> = std::sync::OnceLock::new();
fn __hx_static_cell_sleep_lock(
) -> &'static hxrt::cell::HxCell<crate::HxRef<crate::sys_thread_lock::Lock>> {
    __HX_STATIC_SLEEP_LOCK
        .get_or_init(|| hxrt::cell::HxCell::new(crate::sys_thread_lock::Lock::new()))
}
pub(crate) fn __hx_static_get_sleep_lock() -> crate::HxRef<crate::sys_thread_lock::Lock> {
    __hx_static_cell_sleep_lock().borrow().clone()
}
pub(crate) fn __hx_static_set_sleep_lock(value: crate::HxRef<crate::sys_thread_lock::Lock>) {
    *__hx_static_cell_sleep_lock().borrow_mut() = value;
}

static __HX_STATIC_PENDING: std::sync::OnceLock<
    hxrt::cell::HxCell<
        crate::HxRef<crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>>,
    >,
> = std::sync::OnceLock::new();
fn __hx_static_cell_pending() -> &'static hxrt::cell::HxCell<
    crate::HxRef<crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>>,
> {
    __HX_STATIC_PENDING.get_or_init(|| {
        hxrt::cell::HxCell::new(crate::sys_thread_deque::Deque::<
            crate::HxDynRef<dyn Fn() + Send + Sync>,
        >::new())
    })
}
pub(crate) fn __hx_static_get_pending(
) -> crate::HxRef<crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>> {
    __hx_static_cell_pending().borrow().clone()
}
pub(crate) fn __hx_static_set_pending(
    value: crate::HxRef<crate::sys_thread_deque::Deque<crate::HxDynRef<dyn Fn() + Send + Sync>>>,
) {
    *__hx_static_cell_pending().borrow_mut() = value;
}

static __HX_STATIC_THREAD_COUNT: std::sync::OnceLock<hxrt::cell::HxCell<i32>> =
    std::sync::OnceLock::new();
fn __hx_static_cell_thread_count() -> &'static hxrt::cell::HxCell<i32> {
    __HX_STATIC_THREAD_COUNT.get_or_init(|| hxrt::cell::HxCell::new(0))
}
pub(crate) fn __hx_static_get_thread_count() -> i32 {
    __hx_static_cell_thread_count().borrow().clone()
}
pub(crate) fn __hx_static_set_thread_count(value: i32) {
    *__hx_static_cell_thread_count().borrow_mut() = value;
}

pub const __HX_TYPE_ID: u32 = 0x51a5d353u32;

#[derive(Debug)]
pub struct EntryPoint {}

impl EntryPoint {
    pub fn wakeup() {
        crate::sys_thread_lock::Lock::release(
            &*crate::haxe_entry_point::__hx_static_get_sleep_lock(),
        );
    }

    pub fn run_in_main_thread(f: crate::HxDynRef<dyn Fn() + Send + Sync>) {
        crate::sys_thread_deque::Deque::add(
            &*crate::haxe_entry_point::__hx_static_get_pending(),
            f.clone(),
        );
        crate::haxe_entry_point::EntryPoint::wakeup();
    }

    pub fn add_thread(f: crate::HxDynRef<dyn Fn() + Send + Sync>) {
        crate::sys_thread_mutex::Mutex::acquire(&*crate::haxe_entry_point::__hx_static_get_mutex());
        {
            let __tmp = crate::haxe_entry_point::__hx_static_get_thread_count() + 1;
            crate::haxe_entry_point::__hx_static_set_thread_count(__tmp);
            __tmp
        };
        crate::sys_thread_mutex::Mutex::release(&*crate::haxe_entry_point::__hx_static_get_mutex());
        crate::sys_thread_thread::Thread::create({
            let f = f.clone();
            let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                f();
                crate::sys_thread_mutex::Mutex::acquire(
                    &*crate::haxe_entry_point::__hx_static_get_mutex(),
                );
                {
                    let __tmp = crate::haxe_entry_point::__hx_static_get_thread_count() - 1;
                    crate::haxe_entry_point::__hx_static_set_thread_count(__tmp);
                    __tmp
                };
                let no_threads: bool = crate::haxe_entry_point::__hx_static_get_thread_count() == 0;
                crate::sys_thread_mutex::Mutex::release(
                    &*crate::haxe_entry_point::__hx_static_get_mutex(),
                );
                if no_threads {
                    crate::haxe_entry_point::EntryPoint::wakeup();
                }
            });
            crate::HxDynRef::new(__rc)
        });
    }

    fn process_events() -> f64 {
        loop {
            let f: crate::HxDynRef<dyn Fn() + Send + Sync> = {
                let __hx_opt = crate::sys_thread_deque::Deque::pop(
                    &*crate::haxe_entry_point::__hx_static_get_pending(),
                    false,
                );
                match __hx_opt {
                    Some(__v) => __v,
                    None => crate::HxDynRef::null(),
                }
            };
            if f.is_null() {
                break;
            }
            f();
        }
        let time: f64 = crate::haxe_main_loop::MainLoop::tick();
        if !crate::haxe_main_loop::MainLoop::has_events()
            && crate::haxe_entry_point::__hx_static_get_thread_count() == 0
        {
            return -1 as f64;
        }
        return time;
    }

    pub fn run() {
        loop {
            let next_tick: f64 = crate::haxe_entry_point::EntryPoint::process_events();
            if next_tick < (0 as f64) {
                break;
            }
            if next_tick > (0 as f64) {
                crate::sys_thread_lock::Lock::wait(
                    &*crate::haxe_entry_point::__hx_static_get_sleep_lock(),
                    Some(next_tick),
                );
            }
        }
    }
}
