// Generated by reflaxe.rust

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod fp_helper;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_entry_point;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int32_int32_impl_;
mod haxe_int64_helper;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_main_event;
mod haxe_main_loop;
mod haxe_stack_item;
mod int32_tools;
mod map_storage_tools_nullable;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;
mod sys_thread_deque;
mod sys_thread_event_loop;
mod sys_thread_lock;
mod sys_thread_mutex;
mod sys_thread_next_event_time;
mod sys_thread_thread;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => matches!(expected, 0x44f4c432u32),
        0x39e0cd5bu32 => matches!(expected, 0x44f4c432u32),
        0xd7e07825u32 => matches!(expected, 0x44f4c432u32),
        0x181f937bu32 => matches!(expected, 0x44f4c432u32),
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        _ => false,
    }
}

fn main() {
    let seen: hxrt::array::Array<hxrt::string::HxString> =
        hxrt::array::Array::<hxrt::string::HxString>::new();
    let seen_first: hxrt::array::Array<hxrt::string::HxString> = seen.clone();
    let seen_second: hxrt::array::Array<hxrt::string::HxString> = seen.clone();
    let first: crate::HxRef<crate::HxRef<crate::haxe_main_event::MainEvent>> =
        crate::HxRef::new(crate::HxRef::<crate::haxe_main_event::MainEvent>::null());
    let second: crate::HxRef<crate::HxRef<crate::haxe_main_event::MainEvent>> =
        crate::HxRef::new(crate::HxRef::<crate::haxe_main_event::MainEvent>::null());
    {
        let __tmp = crate::haxe_main_loop::MainLoop::add(
            {
                let seen_first = seen_first.clone();
                let first = first.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    seen_first.push(hxrt::string::HxString::from("first"));
                    crate::haxe_main_event::MainEvent::stop(&*first.borrow().clone());
                });
                crate::HxDynRef::new(__rc)
            },
            0,
        );
        *first.borrow_mut() = __tmp.clone();
        __tmp
    };
    {
        let __tmp = crate::haxe_main_loop::MainLoop::add(
            {
                let seen_second = seen_second.clone();
                let second = second.clone();
                let __rc: crate::HxRc<dyn Fn() + Send + Sync> = crate::HxRc::new(move || {
                    seen_second.push(hxrt::string::HxString::from("second"));
                    crate::haxe_main_event::MainEvent::stop(&*second.borrow().clone());
                });
                crate::HxDynRef::new(__rc)
            },
            0,
        );
        *second.borrow_mut() = __tmp.clone();
        __tmp
    };
    crate::haxe_entry_point::EntryPoint::run();
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(
        seen.join(hxrt::string::HxString::from(",")),
    )));
}
