// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod haxe_ds_list;
mod sys;

fn main() {
    let l: crate::HxRef<crate::haxe_ds_list::List<i32>> = crate::haxe_ds_list::List::<i32>::new();
    crate::haxe_ds_list::List::add(&l, 1);
    crate::haxe_ds_list::List::add(&l, 2);
    crate::haxe_ds_list::List::add(&l, 3);
    let mut sum: i32 = 0;
    for x in crate::haxe_ds_list::List::iterator(&l) {
        {
            sum = sum + x;
            sum
        };
    }
    crate::sys::Sys::println(hxrt::dynamic::from(l.borrow().length));
    crate::sys::Sys::println(hxrt::dynamic::from(sum));
}
