// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_list;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let l: crate::HxRef<crate::haxe_ds_list::List<i32>> = crate::haxe_ds_list::List::<i32>::new();
    crate::haxe_ds_list::List::add(&l, 1);
    crate::haxe_ds_list::List::add(&l, 2);
    crate::haxe_ds_list::List::add(&l, 3);
    let mut sum: i32 = 0;
    for x in crate::haxe_ds_list::List::iterator(&l) {
        {
            sum = sum + x;
            sum
        };
    }
    crate::sys::Sys::println(hxrt::dynamic::from(l.borrow().length));
    crate::sys::Sys::println(hxrt::dynamic::from(sum));
}
