// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod foo;
mod my_enum;
mod sys;
use crate::foo::Foo;
use crate::my_enum::MyEnum;
use crate::sys::Sys;

fn main() {
    println!("{}", String::from("--- Std.string ---"));
    println!("{}", String::from("1"));
    println!("{}", String::from("true"));
    println!("{}", 1.5.to_string());
    println!("{}", String::from("hi"));
    println!("{}", format!("{:?}", Foo::new(3)));
    println!("{}", String::from("--- Std.parseFloat ---"));
    println!(
        "{}",
        hxrt::string::parse_float(String::from("1.25").as_str())
    );
    println!(
        "{}",
        hxrt::string::parse_float(String::from("nope").as_str())
    );
    println!("{}", String::from("--- Type names ---"));
    println!("{}", String::from("Main.Foo"));
    println!("{}", String::from("Main.MyEnum"));
    println!("{}", String::from("--- Bytes ---"));
    let mut b: HxRef<hxrt::bytes::Bytes> = Rc::new(RefCell::new(hxrt::bytes::Bytes::of_string(
        String::from("hi").as_str(),
    )));
    println!("{}", b.borrow().length());
    println!("{}", b.borrow().get(0));
    b.borrow_mut().set(0, 72);
    println!("{}", b.borrow().to_string());
    let mut b2: HxRef<hxrt::bytes::Bytes> =
        Rc::new(RefCell::new(hxrt::bytes::Bytes::alloc((3 as usize))));
    b2.borrow_mut().set(0, 65);
    b2.borrow_mut().set(1, 66);
    b2.borrow_mut().set(2, 67);
    println!("{}", b2.borrow().to_string());
    println!("{}", String::from("--- Option ---"));
    let mut o: Option<i32> = Option::Some(5);
    match o.clone() {
        Option::Some(_) => {
            let mut _g: i32 = match o.clone() {
                Option::Some(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut v: i32 = _g;
                println!("{}", v);
            };
        }
        Option::None => {
            println!("{}", String::from("none"));
        }
        _ => {}
    };
    let mut o2: Option<i32> = Option::None;
    match o2.clone() {
        Option::Some(_) => {
            let mut _g: i32 = match o2.clone() {
                Option::Some(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut v: i32 = _g;
                println!("{}", v);
            };
        }
        Option::None => {
            println!("{}", String::from("none"));
        }
        _ => {}
    };
    println!("{}", String::from("--- Result ---"));
    let mut r: Result<i32, String> = Result::Ok(7);
    match r.clone() {
        Result::Ok(_) => {
            let mut _g: i32 = match r.clone() {
                Result::Ok(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut v: i32 = _g;
                println!("{}", v);
            };
        }
        Result::Err(_) => {
            let mut _g: String = match r.clone() {
                Result::Err(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut e: String = _g;
                println!("{}", e);
            };
        }
        _ => {}
    };
    let mut r2: Result<i32, String> = Result::Err(String::from("fail").clone());
    match r2.clone() {
        Result::Ok(_) => {
            let mut _g: i32 = match r2.clone() {
                Result::Ok(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut v: i32 = _g;
                println!("{}", v);
            };
        }
        Result::Err(_) => {
            let mut _g: String = match r2.clone() {
                Result::Err(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut e: String = _g;
                println!("{}", e);
            };
        }
        _ => {}
    };
    println!("{}", String::from("--- Reflect ---"));
    let mut foo: HxRef<Foo> = Foo::new(9);
    println!("{}", foo.borrow().x);
    println!("{:?}", hxrt::dynamic::from(foo.borrow().x.clone()));
    {
        {
            let __tmp = 42;
            foo.borrow_mut().x = __tmp.clone();
            __tmp
        };
    };
    println!("{}", foo.borrow().x);
}
