// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xec47dd96u32;

#[derive(Debug)]
pub struct Helpers {}

impl Helpers {
    pub fn make<T: Clone + Send + Sync>(value: T) -> crate::HxRef<crate::payload::Payload<T>> {
        return crate::payload::Payload::<T>::new(value);
    }

    pub fn read<T: Clone + Send + Sync>(payload: crate::HxRef<crate::payload::Payload<T>>) -> T {
        return {
            let __b = payload.borrow();
            __b.value.clone()
        };
    }
}
