// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod action;
mod task;
mod tui_demo;

fn main() {
    let tasks: Vec<crate::HxRef<crate::task::Task>> = vec![
        crate::task::Task::new(String::from("bootstrap reflaxe.rust"), true),
        crate::task::Task::new(String::from("add enums + switch"), false),
        crate::task::Task::new(String::from("ship ratatui demo"), false),
    ];
    let actions: Vec<crate::action::Action> = vec![
        crate::action::Action::Down,
        crate::action::Action::Toggle,
        crate::action::Action::Down,
        crate::action::Action::Toggle,
        crate::action::Action::Up,
        crate::action::Action::Quit,
    ];
    let mut selected: i32 = 0;
    let mut frame: i32 = 0;
    let mut i: i32 = 0;
    while i < actions.len() as i32 {
        let action: crate::action::Action = actions[i as usize].clone();
        match action.clone() {
            crate::action::Action::Up => {
                if selected > 0 {
                    selected = selected - 1;
                };
            }
            crate::action::Action::Down => {
                if selected < tasks.len() as i32 - 1 {
                    selected = selected + 1;
                };
            }
            crate::action::Action::Toggle => {
                crate::task::Task::toggle(&tasks[selected as usize].clone());
            }
            crate::action::Action::Quit => {
                break;
            }
        };
        let mut lines: String = String::from("");
        let mut j: i32 = 0;
        while j < tasks.len() as i32 {
            lines = format!(
                "{}{}",
                format!(
                    "{}{}",
                    lines,
                    crate::task::Task::line(&tasks[j as usize].clone(), j == selected)
                ),
                String::from("\n")
            );
            j = j + 1;
        }
        crate::tui_demo::run_frame(frame, lines.clone());
        frame = frame + 1;
        i = i + 1;
    }
}
