// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xd29a96adu32;

#[derive(Clone, Debug, PartialEq)]
pub enum StyleToken {
    Normal,
    Muted,
    Title,
    Accent,
    Selected,
    Success,
    Warning,
    Danger,
}
