// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xad9a8cc0u32;

#[derive(Debug)]

pub struct Task {
    pub text: hxrt::string::HxString,
    pub done: bool,
}

impl Task {
    pub fn new(text: hxrt::string::HxString, done: bool) -> crate::HxRef<crate::task::Task> {
        let self_: crate::HxRef<crate::task::Task> = crate::HxRef::new(Task {
            text: text,
            done: done,
        });
        return self_;
    }

    pub fn toggle(self_: &crate::HxRefCell<Task>) {
        let __hx_this: crate::HxRef<crate::task::Task> = self_.self_ref();
        {
            let __tmp = !({
                let __b = __hx_this.borrow();
                __b.done
            });
            __hx_this.borrow_mut().done = __tmp;
            __tmp
        };
    }

    pub fn line(self_: &crate::HxRefCell<Task>, selected: bool) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::task::Task> = self_.self_ref();
        let sel: hxrt::string::HxString = hxrt::string::HxString::from(if selected {
            hxrt::string::HxString::from(">")
        } else {
            hxrt::string::HxString::from(" ")
        });
        let mark: hxrt::string::HxString = hxrt::string::HxString::from(
            if {
                let __b = __hx_this.borrow();
                __b.done
            } {
                hxrt::string::HxString::from("x")
            } else {
                hxrt::string::HxString::from(" ")
            },
        );
        return hxrt::string::HxString::from(hxrt::string::HxString::from(format!(
            "{}{}{}{}{}",
            &sel,
            "[",
            &mark,
            "] ",
            &__hx_this.borrow().text
        )));
    }
}
