// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod base;
mod derived;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let b: crate::HxRc<dyn crate::base::BaseTrait + Send + Sync> = crate::base::Base::new();
    println!("{}", hxrt::dynamic::from(b.set_x(7)));
    println!("{}", hxrt::dynamic::from(b.__hx_get_x()));
    println!(
        "{}",
        hxrt::dynamic::from({
            let postfix: i32 = b.__hx_get_x();
            b.set_x(b.__hx_get_x() + 1);
            postfix
        })
    );
    println!("{}", hxrt::dynamic::from(b.__hx_get_x()));
    println!("{}", hxrt::dynamic::from(b.set_x(b.__hx_get_x() + 1)));
    println!("{}", hxrt::dynamic::from(b.__hx_get_x()));
    println!("{}", hxrt::dynamic::from(b.set_y(3)));
    println!("{}", hxrt::dynamic::from(b.get_y()));
    b.set_y(b.get_y() + 2);
    println!("{}", hxrt::dynamic::from(b.get_y()));
    let p: crate::HxRc<dyn crate::base::BaseTrait + Send + Sync> = crate::derived::Derived::new();
    println!("{}", hxrt::dynamic::from(p.set_y(3)));
    println!("{}", hxrt::dynamic::from(p.get_y()));
}
