// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x2a7dcad8u32;

#[derive(Debug)]

pub struct StringIteratorUnicode {
    offset: i32,
    s: hxrt::string::HxString,
}

impl StringIteratorUnicode {
    pub fn new(
        s: hxrt::string::HxString,
    ) -> crate::HxRef<crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode> {
        let self_: crate::HxRef<
            crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode,
        > = crate::HxRef::new(StringIteratorUnicode { offset: 0, s: s });
        return self_;
    }

    pub fn has_next(self_: &crate::HxRefCell<StringIteratorUnicode>) -> bool {
        let __hx_this: crate::HxRef<
            crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode,
        > = self_.self_ref();
        return ({
            let __b = __hx_this.borrow();
            __b.offset
        }) < hxrt::string::len(
            ({
                let __b = __hx_this.borrow();
                __b.s.clone()
            })
            .as_str(),
        );
    }

    pub fn next(self_: &crate::HxRefCell<StringIteratorUnicode>) -> i32 {
        let __hx_this: crate::HxRef<
            crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode,
        > = self_.self_ref();
        return crate::string_tools::StringTools::fast_code_at(
            hxrt::string::HxString::from({
                let __b = __hx_this.borrow();
                __b.s.clone()
            }),
            {
                let __tmp = self_.borrow().offset;
                self_.borrow_mut().offset = __tmp + 1;
                __tmp
            },
        );
    }

    pub fn unicode_iterator(
        s: hxrt::string::HxString,
    ) -> crate::HxRef<crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode> {
        return crate::haxe_iterators_string_iterator_unicode::StringIteratorUnicode::new(
            hxrt::string::HxString::from(s),
        );
    }
}
