// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn main() {
    let a: i32 = 1;
    let b: i32 = 2;
    let c: i32 = a + b;
    println!("{}", hxrt::dynamic::from(c));
    let mut i: i32 = 0;
    while i < 2 {
        i = i + 1;
    }
}
