// Generated by reflaxe.rust

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod fp_helper;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int32_int32_impl_;
mod haxe_int64_helper;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_stack_item;
mod int32_tools;
mod map_storage_tools_nullable;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => expected == 0x44f4c432u32,
        0x39e0cd5bu32 => expected == 0x44f4c432u32,
        0xd7e07825u32 => expected == 0x44f4c432u32,
        0x181f937bu32 => expected == 0x44f4c432u32,
        0x163b1f5au32 => expected == 0xe82620b4u32,
        0xfb16179cu32 => expected == 0xd50291cbu32,
        0x9402c169u32 => expected == 0xe82620b4u32,
        _ => false,
    }
}

fn make_missing() -> crate::HxRef<hxrt::anon::Anon> {
    return {
        let __o = crate::HxRef::new(hxrt::anon::Anon::new());
        {
            let mut __b = __o.borrow_mut();
            __b.set("name", hxrt::string::HxString::from("Ada"));
        };
        __o
    };
}

fn make_present() -> crate::HxRef<hxrt::anon::Anon> {
    return {
        let __o = crate::HxRef::new(hxrt::anon::Anon::new());
        {
            let mut __b = __o.borrow_mut();
            __b.set("name", hxrt::string::HxString::from("Grace"));
            __b.set("nickname", hxrt::string::HxString::from("Amazing"));
            __b.set("enabled", Some(true));
        };
        __o
    };
}

fn describe(p: crate::HxRef<hxrt::anon::Anon>) -> hxrt::string::HxString {
    let nick: hxrt::string::HxString = hxrt::string::HxString::from(
        if ({
            let __b = p.borrow();
            if __b.has_key("nickname") {
                __b.get::<hxrt::string::HxString>("nickname")
            } else {
                hxrt::string::HxString::null()
            }
        })
        .is_null()
        {
            hxrt::string::HxString::from("<missing>")
        } else {
            hxrt::string::HxString::from({
                let __b = p.borrow();
                if __b.has_key("nickname") {
                    __b.get::<hxrt::string::HxString>("nickname")
                } else {
                    hxrt::string::HxString::null()
                }
            })
        },
    );
    let active: hxrt::string::HxString = hxrt::string::HxString::from(
        if ({
            let __b = p.borrow();
            if __b.has_key("enabled") {
                __b.get::<Option<bool>>("enabled")
            } else {
                None
            }
        }) == Some(true)
        {
            hxrt::string::HxString::from("enabled")
        } else {
            hxrt::string::HxString::from("disabled-or-missing")
        },
    );
    return hxrt::string::HxString::from(format!(
        "{}{}{}{}{}",
        p.borrow().get::<hxrt::string::HxString>("name"),
        ":",
        &nick,
        ":",
        &active
    ));
}

fn main() {
    let missing: crate::HxRef<hxrt::anon::Anon> = make_missing();
    crate::sys::Sys::println(hxrt::dynamic::from(
        missing.borrow().get::<hxrt::string::HxString>("name"),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(
        ({
            let __b = missing.borrow();
            if __b.has_key("nickname") {
                __b.get::<hxrt::string::HxString>("nickname")
            } else {
                hxrt::string::HxString::null()
            }
        })
        .is_null(),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(
        ({
            let __b = missing.borrow();
            if __b.has_key("enabled") {
                __b.get::<Option<bool>>("enabled")
            } else {
                None
            }
        })
        .is_none(),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(describe(missing.clone())));
    let present: crate::HxRef<hxrt::anon::Anon> = make_present();
    crate::sys::Sys::println(hxrt::dynamic::from(
        present.borrow().get::<hxrt::string::HxString>("name"),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(
        ({
            let __b = present.borrow();
            if __b.has_key("nickname") {
                __b.get::<hxrt::string::HxString>("nickname")
            } else {
                hxrt::string::HxString::null()
            }
        })
        .is_null(),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(
        ({
            let __b = present.borrow();
            if __b.has_key("enabled") {
                __b.get::<Option<bool>>("enabled")
            } else {
                None
            }
        })
        .is_none(),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(describe(present.clone())));
}
