// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn bump(a: hxrt::array::Array<i32>) {
    a.push(99);
}

fn main() {
    let a: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1]);
    let b: hxrt::array::Array<i32> = a.clone();
    b.push(2);
    crate::sys::Sys::println(hxrt::dynamic::from(a.len() as i32));
    bump(a.clone());
    crate::sys::Sys::println(hxrt::dynamic::from(a.len() as i32));
    crate::sys::Sys::println(hxrt::dynamic::from(b.len() as i32));
}
