// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn add1(x: i32) -> i32 {
    return x + 1;
}

fn apply(f: crate::HxDynRef<dyn Fn(i32) -> i32 + Send + Sync>, x: i32) -> i32 {
    return f(x);
}

fn main() {
    let f: crate::HxDynRef<dyn Fn(i32) -> i32 + Send + Sync> = {
        let __rc: crate::HxRc<dyn Fn(i32) -> i32 + Send + Sync> = crate::HxRc::new(add1);
        crate::HxDynRef::new(__rc)
    };
    println!("{}", hxrt::dynamic::from(f(5)));
    let g: crate::HxDynRef<dyn Fn(i32) -> i32 + Send + Sync> = {
        let __rc: crate::HxRc<dyn Fn(i32) -> i32 + Send + Sync> =
            crate::HxRc::new(move |x: i32| {
                return x * 2;
            });
        crate::HxDynRef::new(__rc)
    };
    println!("{}", hxrt::dynamic::from(apply(g, 3)));
}
