// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn add1(x: i32) -> i32 {
    return x + 1;
}

fn apply(f: std::rc::Rc<dyn Fn(i32) -> i32>, x: i32) -> i32 {
    return f(x);
}

fn main() {
    let f: std::rc::Rc<dyn Fn(i32) -> i32> = std::rc::Rc::new(move |a0: i32| add1(a0));
    println!("{}", f(5));
    let g: std::rc::Rc<dyn Fn(i32) -> i32> = std::rc::Rc::new(move |x: i32| {
        return x * 2;
    });
    println!("{}", apply(std::rc::Rc::new(move |a0: i32| { g(a0) }), 3));
}
