// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn add1(x: i32) -> i32 {
    return x + 1;
}

fn apply(f: std::rc::Rc<dyn Fn(i32) -> i32>, x: i32) -> i32 {
    return f(x);
}

fn main() {
    let f: std::rc::Rc<dyn Fn(i32) -> i32> = std::rc::Rc::new(move |a0: i32| add1(a0));
    println!("{}", hxrt::dynamic::from(f(5)));
    let g: std::rc::Rc<dyn Fn(i32) -> i32> = std::rc::Rc::new(move |x: i32| {
        return x * 2;
    });
    println!(
        "{}",
        hxrt::dynamic::from(apply(std::rc::Rc::new(move |a0: i32| { g(a0) }), 3))
    );
}
