// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod rust_iter_tools;
mod rust_vec_tools;
mod sys;

fn is_even(n: i32) -> bool {
    return n / 2 * 2 == n;
}

fn parse_even(n: i32) -> Result<i32, String> {
    return if is_even(n) {
        Result::Ok(n)
    } else {
        Result::Err(String::from("odd"))
    };
}

fn main() {
    let mut v: Vec<i32> = Vec::<i32>::new();
    v.push(1);
    v.push(2);
    println!("{}", crate::rust_vec_tools::VecTools::len(v.clone()));
    let last: Option<i32> = v.pop();
    match last.clone() {
        Option::Some(__p) => {
            let _g: i32 = __p;
            {
                let x: i32 = _g;
                println!("{}", x);
            }
        }
        Option::None => {
            println!("{}", -1);
        }
    }
    {
        let _g_2: Result<i32, String> = parse_even(2);
        match _g_2.clone() {
            Result::Ok(__p) => {
                let _g_3: i32 = __p;
                {
                    let x_2: i32 = _g_3;
                    println!("{}", x_2);
                }
            }
            Result::Err(__p) => {
                let _g_4: String = __p;
                {
                    let e: String = _g_4;
                    println!("{}", e);
                }
            }
        }
    }
    let mut v2: Vec<i32> = Vec::<i32>::new();
    v2.push(10);
    v2.push(20);
    let mut sum: i32 = 0;
    for x_3 in crate::rust_iter_tools::IterTools::from_vec(v2).into_iter() {
        sum = sum + x_3;
    }
    println!("{}", sum);
}
