// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod rust_vec_tools;
mod sys;
use crate::rust_vec_tools::VecTools;
use crate::sys::Sys;

fn is_even(n: i32) -> bool {
    return n / 2 * 2 == n;
}

fn parse_even(n: i32) -> Result<i32, String> {
    return if is_even(n) {
        Result::Ok(n)
    } else {
        Result::Err(String::from("odd").clone())
    };
}

fn main() {
    let mut v: Vec<i32> = Vec::new();
    v.push(1);
    v.push(2);
    println!("{}", VecTools::len(v.clone()));
    let mut last: Option<i32> = v.pop();
    match last.clone() {
        Option::Some(_) => {
            let mut _g: i32 = match last.clone() {
                Option::Some(__p) => __p,
                _ => unreachable!(),
            };
            {
                let mut x: i32 = _g;
                println!("{}", x);
            };
        }
        Option::None => {
            println!("{}", -1);
        }
    };
    {
        let mut _g: Result<i32, String> = parse_even(2);
        match _g.clone() {
            Result::Ok(_) => {
                let mut _g: i32 = match _g.clone() {
                    Result::Ok(__p) => __p,
                    _ => unreachable!(),
                };
                {
                    let mut x: i32 = _g;
                    println!("{}", x);
                };
            }
            Result::Err(_) => {
                let mut _g: String = match _g.clone() {
                    Result::Err(__p) => __p,
                    _ => unreachable!(),
                };
                {
                    let mut e: String = _g;
                    println!("{}", e);
                };
            }
        };
    };
}
