// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let xs: hxrt::array::Array<String> = hxrt::array::Array::<String>::from_vec(vec![
        String::from("a"),
        String::from("b"),
        String::from("c"),
    ]);
    xs.insert(-1, String::from("X"));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from("")).clone()));
    xs.insert(-100, String::from("Y"));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from("")).clone()));
    xs.insert(999, String::from("Z"));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from("")).clone()));
}
