// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x89178131u32;

#[derive(Debug)]
pub struct Parent {
    pub child: crate::HxRef<crate::child::Child>,
}

impl Parent {
    pub fn new(fields: crate::HxRef<hxrt::anon::Anon>) -> crate::HxRef<crate::parent::Parent> {
        let self_: crate::HxRef<crate::parent::Parent> = crate::HxRef::new(Parent {
            child: crate::HxRef::null(),
        });
        let provided: crate::HxRef<crate::child::Child> = fields
            .borrow()
            .get::<crate::HxRef<crate::child::Child>>("child");
        {
            let __tmp = provided;
            self_.borrow_mut().child = __tmp.clone();
            __tmp
        };
        return self_;
    }
}
