// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x2263869cu32;

#[derive(Debug)]
pub struct ParentWithDefaultChild {
    pub child: crate::HxRef<crate::child::Child>,
}

impl ParentWithDefaultChild {
    pub fn new() -> crate::HxRef<crate::parent_with_default_child::ParentWithDefaultChild> {
        let self_: crate::HxRef<crate::parent_with_default_child::ParentWithDefaultChild> =
            crate::HxRef::new(ParentWithDefaultChild {
                child: crate::HxRef::null(),
            });
        return self_;
    }
}
