// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xc6e4ba7fu32;

#[derive(Debug)]
pub struct GreeterRunner {}

impl GreeterRunner {
    pub fn run(greeter: crate::HxRc<dyn crate::greeter::Greeter + Send + Sync>) -> String {
        return greeter.greet();
    }
}
