// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x6fc4364eu32;

#[derive(Debug)]
pub struct PersonGreeter {
    pub name: String,
}

impl PersonGreeter {
    pub fn new(name: String) -> crate::HxRef<crate::person_greeter::PersonGreeter> {
        let self_: crate::HxRef<crate::person_greeter::PersonGreeter> =
            crate::HxRef::new(PersonGreeter { name: name });
        return self_;
    }

    pub fn greet(self_: &crate::HxRefCell<PersonGreeter>) -> String {
        let __hx_this: crate::HxRef<crate::person_greeter::PersonGreeter> = self_.self_ref();
        return format!("{}{}", "hello ", &__hx_this.borrow().name);
    }
}

impl crate::greeter::Greeter for crate::HxRefCell<PersonGreeter> {
    fn greet(&self) -> String {
        PersonGreeter::greet(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::person_greeter::__HX_TYPE_ID
    }
}
