// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x285d6471u32;

#[derive(Debug)]

pub struct Host {
    pub host: hxrt::string::HxString,
    pub ip: i32,
}

impl Host {
    pub fn new(name: hxrt::string::HxString) -> crate::HxRef<crate::sys_net_host::Host> {
        let self_: crate::HxRef<crate::sys_net_host::Host> = crate::HxRef::new(Host {
            host: name.clone(),
            ip: crate::socket_native::host_resolve(&name.clone()),
        });
        return self_;
    }

    pub fn to_string(self_: &crate::HxRefCell<Host>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::sys_net_host::Host> = self_.self_ref();
        return hxrt::string::HxString::from(crate::socket_native::host_to_string({
            let __b = __hx_this.borrow();
            __b.ip
        }));
    }

    pub fn reverse(self_: &crate::HxRefCell<Host>) -> hxrt::string::HxString {
        let __hx_this: crate::HxRef<crate::sys_net_host::Host> = self_.self_ref();
        return hxrt::string::HxString::from(crate::socket_native::host_reverse({
            let __b = __hx_this.borrow();
            __b.ip
        }));
    }

    pub fn localhost() -> hxrt::string::HxString {
        return hxrt::string::HxString::from(crate::socket_native::host_local());
    }
}
