// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod rust_borrow;
mod rust_hash_map_tools;
mod sys;
use crate::rust_borrow::Borrow;
use crate::rust_hash_map_tools::HashMapTools;
use crate::sys::Sys;

fn main() {
    let mut m: std::collections::HashMap<String, i32> = std::collections::HashMap::new();
    m.insert(String::from("a"), 1);
    m.insert(String::from("b"), 2);
    let mut key: String = String::from("b");
    {
        let mut k: &String = &key;
        {
            let mut v: Option<&i32> = m.get(k);
            match v.clone() {
                Option::Some(_) => {
                    let mut _g: &i32 = match v.clone() {
                        Option::Some(__p) => __p,
                        _ => unreachable!(),
                    };
                    {
                        let mut x: &i32 = _g;
                        println!("{:?}", x);
                    };
                }
                Option::None => {
                    println!("{}", -1);
                }
            };
        };
    };
    println!("{}", HashMapTools::len(m));
}
