// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x6cc99212u32;

#[derive(Debug)]

pub struct HashMapTools {}

impl HashMapTools {
    pub fn len<K, V>(m: std::collections::HashMap<K, V>) -> i32 {
        return m.len() as i32;
    }
}
