// Generated by reflaxe.rust

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_exception;
mod haxe_stack_item;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    false
}

fn narrow(value: Option<i32>) -> i32 {
    return match value {
        None => -1,
        Some(__hx_value) => __hx_value,
    };
}

fn narrow_float(value: Option<f64>) -> f64 {
    return match value {
        None => -1.5,
        Some(__hx_value) => __hx_value,
    };
}

fn main() {
    if narrow(Some(7)) != 7 {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "non-null narrowing failed",
        )));
    }
    if narrow(None) != -1 {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "null narrowing failed",
        )));
    }
    if narrow_float(Some(2.5)) != 2.5 {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "non-null Float narrowing failed",
        )));
    }
    if narrow_float(None) != -1.5 {
        hxrt::exception::throw(hxrt::dynamic::from(hxrt::string::HxString::from(
            "null Float narrowing failed",
        )));
    }
}
