// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let mut o2_x: i32;
    let mut o2_s: String;
    o2_x = 1;
    o2_s = String::from("hi");
    println!("{}", hxrt::dynamic::from(o2_x));
    println!("{}", hxrt::dynamic::from(o2_s.clone()));
    o2_x = 2;
    println!("{}", hxrt::dynamic::from(o2_x));
    {
        o2_x = o2_x + 3;
        o2_x
    };
    println!("{}", hxrt::dynamic::from(o2_x));
    println!(
        "{}",
        hxrt::dynamic::from({
            let __tmp = o2_x;
            o2_x = o2_x + 1;
            __tmp
        })
    );
    println!("{}", hxrt::dynamic::from(o2_x));
    {
        let __tmp = o2_x;
        o2_x = o2_x - 1;
        __tmp
    };
    println!("{}", hxrt::dynamic::from(o2_x));
    o2_s = format!("{}{}", &o2_s, "!");
    println!("{}", hxrt::dynamic::from(o2_s.clone()));
}
