// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod rust_array_borrow;
mod rust_mut_slice_tools;
mod rust_slice_tools;
mod sys;

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3]);
    crate::rust_array_borrow::ArrayBorrow::with_slice(
        xs.clone(),
        std::rc::Rc::new(move |_hx_slice: &[i32]| {
            let s: &[i32] = _hx_slice;
            {
                crate::sys::Sys::println(hxrt::dynamic::from(
                    crate::rust_slice_tools::SliceTools::len(s),
                ));
                return;
            }
        }),
    );
    crate::rust_array_borrow::ArrayBorrow::with_mut_slice(
        xs.clone(),
        std::rc::Rc::new(move |_hx_slice: &mut [i32]| {
            let s: &mut [i32] = _hx_slice;
            {
                crate::rust_mut_slice_tools::MutSliceTools::set(s, 1, 99);
                return;
            }
        }),
    );
    crate::sys::Sys::println(hxrt::dynamic::from(xs.get_unchecked(1 as usize)));
}
