// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod rust_array_borrow;
mod rust_mut_slice_tools;
mod rust_slice_tools;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3]);
    crate::rust_array_borrow::ArrayBorrow::with_slice(xs.clone(), {
        let __rc: crate::HxRc<dyn Fn(&[i32]) + Send + Sync> =
            crate::HxRc::new(move |_hx_slice: &[i32]| {
                let s: &[i32] = _hx_slice;
                {
                    crate::sys::Sys::println(hxrt::dynamic::from(
                        crate::rust_slice_tools::SliceTools::len(s),
                    ));
                    return;
                }
            });
        crate::HxDynRef::new(__rc)
    });
    crate::rust_array_borrow::ArrayBorrow::with_mut_slice(xs.clone(), {
        let __rc: crate::HxRc<dyn Fn(&mut [i32]) + Send + Sync> =
            crate::HxRc::new(move |_hx_slice: &mut [i32]| {
                let s: &mut [i32] = _hx_slice;
                {
                    crate::rust_mut_slice_tools::MutSliceTools::set(s, 1, 99);
                    return;
                }
            });
        crate::HxDynRef::new(__rc)
    });
    crate::sys::Sys::println(hxrt::dynamic::from(xs.get_unchecked(1 as usize)));
}
