// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = std::rc::Rc<T>;
type HxRefCell<T> = std::cell::RefCell<T>;
type HxRef<T> = HxRc<HxRefCell<T>>;

mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod rust_array_borrow;
mod rust_mut_slice_tools;
mod rust_slice_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3]);
    crate::rust_array_borrow::ArrayBorrow::with_slice(
        xs.clone(),
        crate::HxRc::new(move |_hx_slice: &[i32]| {
            let s: &[i32] = _hx_slice;
            {
                crate::sys::Sys::println(hxrt::dynamic::from(
                    crate::rust_slice_tools::SliceTools::len(s),
                ));
                return;
            }
        }),
    );
    crate::rust_array_borrow::ArrayBorrow::with_mut_slice(
        xs.clone(),
        crate::HxRc::new(move |_hx_slice: &mut [i32]| {
            let s: &mut [i32] = _hx_slice;
            {
                crate::rust_mut_slice_tools::MutSliceTools::set(s, 1, 99);
                return;
            }
        }),
    );
    crate::sys::Sys::println(hxrt::dynamic::from(xs.get_unchecked(1 as usize)));
}
