// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x9fd02219u32;

#[derive(Debug)]

pub struct ReflaxeStdAdapters {}

impl ReflaxeStdAdapters {
    pub fn to_rust_option<T>(value: Option<T>) -> Option<T> {
        return value;
    }

    pub fn from_rust_option<T>(value: Option<T>) -> Option<T> {
        return value;
    }

    pub fn to_rust_result<T, E>(value: Result<T, E>) -> Result<T, E> {
        return value;
    }

    pub fn from_rust_result<T, E>(value: Result<T, E>) -> Result<T, E> {
        return value;
    }
}
