// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod e;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod key;
mod sys;

fn main() {
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- StringMap<Int> ---"))
    );
    let sm: crate::HxRef<crate::haxe_ds_string_map::StringMap<i32>> =
        crate::haxe_ds_string_map::StringMap::<i32>::new();
    crate::haxe_ds_string_map::StringMap::set(&sm, String::from("a"), 1);
    crate::haxe_ds_string_map::StringMap::set(&sm, String::from("b"), 2);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::exists(
            &sm,
            String::from("a")
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::exists(
            &sm,
            String::from("z")
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(
            crate::haxe_ds_string_map::StringMap::get(&sm, String::from("a")).is_none()
        )
    );
    println!(
        "{}",
        hxrt::dynamic::from(
            crate::haxe_ds_string_map::StringMap::get(&sm, String::from("z")).is_none()
        )
    );
    for k in crate::haxe_ds_string_map::StringMap::keys(&sm) {
        println!("{}", hxrt::dynamic::from(format!("{}{}", "k=", &k).clone()));
    }
    for v in crate::haxe_ds_string_map::StringMap::iterator(&sm) {
        println!("{}", hxrt::dynamic::from(format!("{}{}", "v=", v).clone()));
    }
    for kv in crate::haxe_ds_string_map::StringMap::key_value_iterator(&sm) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}{}", kv.key, "=>", kv.value).clone())
        );
    }
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::remove(
            &sm,
            String::from("a")
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::exists(
            &sm,
            String::from("a")
        ))
    );
    let sm2: crate::HxRef<crate::haxe_ds_string_map::StringMap<i32>> =
        crate::haxe_ds_string_map::StringMap::copy(&sm);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::exists(
            &sm2,
            String::from("b")
        ))
    );
    crate::haxe_ds_string_map::StringMap::clear(&sm);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_string_map::StringMap::exists(
            &sm,
            String::from("b")
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- IntMap<Int> ---"))
    );
    let im: crate::HxRef<crate::haxe_ds_int_map::IntMap<i32>> =
        crate::haxe_ds_int_map::IntMap::<i32>::new();
    crate::haxe_ds_int_map::IntMap::set(&im, 10, 7);
    crate::haxe_ds_int_map::IntMap::set(&im, 20, 9);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_int_map::IntMap::exists(&im, 10))
    );
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_int_map::IntMap::get(&im, 10).is_none())
    );
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_int_map::IntMap::get(&im, 999).is_none())
    );
    for k_2 in crate::haxe_ds_int_map::IntMap::keys(&im) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}", "k=", k_2).clone())
        );
    }
    for v_2 in crate::haxe_ds_int_map::IntMap::iterator(&im) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}", "v=", v_2).clone())
        );
    }
    for kv_2 in crate::haxe_ds_int_map::IntMap::key_value_iterator(&im) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}{}", kv_2.key, "=>", kv_2.value).clone())
        );
    }
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- ObjectMap<Key, Int> ---"))
    );
    let om: crate::HxRef<crate::haxe_ds_object_map::ObjectMap<crate::HxRef<crate::key::Key>, i32>> =
        crate::haxe_ds_object_map::ObjectMap::<crate::HxRef<crate::key::Key>, i32>::new();
    let k1: crate::HxRef<crate::key::Key> = crate::key::Key::new(1);
    let k2: crate::HxRef<crate::key::Key> = crate::key::Key::new(2);
    crate::haxe_ds_object_map::ObjectMap::set(&om, k1.clone(), 100);
    crate::haxe_ds_object_map::ObjectMap::set(&om, k2.clone(), 200);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_object_map::ObjectMap::exists(
            &om,
            k1.clone()
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_object_map::ObjectMap::get(&om, k1.clone()).is_none())
    );
    println!(
        "{}",
        hxrt::dynamic::from(
            crate::haxe_ds_object_map::ObjectMap::get(&om, crate::key::Key::new(1)).is_none()
        )
    );
    for k_3 in crate::haxe_ds_object_map::ObjectMap::keys(&om) {
        println!(
            "{}",
            hxrt::dynamic::from(
                format!(
                    "{}{}",
                    "k=",
                    hxrt::dynamic::from(k_3.clone()).to_haxe_string()
                )
                .clone()
            )
        );
    }
    for v_3 in crate::haxe_ds_object_map::ObjectMap::iterator(&om) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}", "v=", v_3).clone())
        );
    }
    for kv_3 in crate::haxe_ds_object_map::ObjectMap::key_value_iterator(&om) {
        println!(
            "{}",
            hxrt::dynamic::from(
                format!(
                    "{}{}{}",
                    hxrt::dynamic::from(kv_3.key.clone()).to_haxe_string(),
                    "=>",
                    kv_3.value
                )
                .clone()
            )
        );
    }
    println!(
        "{}",
        hxrt::dynamic::from(String::from("--- EnumValueMap<E, Int> ---"))
    );
    let em: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<crate::e::E, i32>> =
        crate::haxe_ds_enum_value_map::EnumValueMap::<crate::e::E, i32>::new();
    crate::haxe_ds_enum_value_map::EnumValueMap::set(&em, crate::e::E::A, 1);
    crate::haxe_ds_enum_value_map::EnumValueMap::set(&em, crate::e::E::B(3), 9);
    println!(
        "{}",
        hxrt::dynamic::from(crate::haxe_ds_enum_value_map::EnumValueMap::exists(
            &em,
            crate::e::E::A
        ))
    );
    println!(
        "{}",
        hxrt::dynamic::from(
            crate::haxe_ds_enum_value_map::EnumValueMap::get(&em, crate::e::E::A).is_none()
        )
    );
    println!(
        "{}",
        hxrt::dynamic::from(
            crate::haxe_ds_enum_value_map::EnumValueMap::get(&em, crate::e::E::B(999)).is_none()
        )
    );
    for k_4 in crate::haxe_ds_enum_value_map::EnumValueMap::keys(&em) {
        println!(
            "{}",
            hxrt::dynamic::from(
                format!(
                    "{}{}",
                    "k=",
                    hxrt::dynamic::from(k_4.clone()).to_haxe_string()
                )
                .clone()
            )
        );
    }
    for v_4 in crate::haxe_ds_enum_value_map::EnumValueMap::iterator(&em) {
        println!(
            "{}",
            hxrt::dynamic::from(format!("{}{}", "v=", v_4).clone())
        );
    }
    for kv_4 in crate::haxe_ds_enum_value_map::EnumValueMap::key_value_iterator(&em) {
        println!(
            "{}",
            hxrt::dynamic::from(
                format!(
                    "{}{}{}",
                    hxrt::dynamic::from(kv_4.key.clone()).to_haxe_string(),
                    "=>",
                    kv_4.value
                )
                .clone()
            )
        );
    }
}
