// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x39e0cd5bu32;

#[derive(Debug)]

pub struct IntMap<T: Clone + std::fmt::Debug> {
    h: std::collections::HashMap<i32, T>,
}

impl<T: Clone + std::fmt::Debug> IntMap<T> {
    pub fn new() -> crate::HxRef<crate::haxe_ds_int_map::IntMap<T>> {
        let self_: crate::HxRef<crate::haxe_ds_int_map::IntMap<T>> =
            crate::HxRc::new(crate::HxRefCell::new(IntMap {
                h: std::collections::HashMap::<i32, T>::new(),
            }));
        return self_;
    }

    pub fn set(self_: &crate::HxRefCell<IntMap<T>>, key: i32, value: T) {
        self_.borrow_mut().h.insert(key, value);
    }

    pub fn get(self_: &crate::HxRefCell<IntMap<T>>, key: i32) -> Option<T> {
        return self_.borrow().h.get(&key).cloned();
    }

    pub fn exists(self_: &crate::HxRefCell<IntMap<T>>, key: i32) -> bool {
        return self_.borrow().h.contains_key(&key);
    }

    pub fn remove(self_: &crate::HxRefCell<IntMap<T>>, key: i32) -> bool {
        return self_.borrow_mut().h.remove(&key).is_some();
    }

    pub fn keys(self_: &crate::HxRefCell<IntMap<T>>) -> hxrt::iter::Iter<i32> {
        return hxrt::iter::Iter::from_vec(self_.borrow().h.keys().cloned().collect::<Vec<_>>());
    }

    pub fn iterator(self_: &crate::HxRefCell<IntMap<T>>) -> hxrt::iter::Iter<T> {
        return hxrt::iter::Iter::from_vec(self_.borrow().h.values().cloned().collect::<Vec<_>>());
    }

    pub fn key_value_iterator(
        self_: &crate::HxRefCell<IntMap<T>>,
    ) -> hxrt::iter::Iter<hxrt::iter::KeyValue<i32, T>> {
        return hxrt::iter::Iter::from_vec(
            self_
                .borrow()
                .h
                .iter()
                .map(|(k, v)| hxrt::iter::KeyValue {
                    key: k.clone(),
                    value: v.clone(),
                })
                .collect::<Vec<_>>(),
        );
    }

    pub fn copy(
        self_: &crate::HxRefCell<IntMap<T>>,
    ) -> crate::HxRef<crate::haxe_ds_int_map::IntMap<T>> {
        let out: crate::HxRef<crate::haxe_ds_int_map::IntMap<T>> =
            crate::haxe_ds_int_map::IntMap::<T>::new();
        out.borrow_mut().h = self_.borrow().h.clone();
        return out;
    }

    pub fn to_string(self_: &crate::HxRefCell<IntMap<T>>) -> String {
        return format!("{:?}", self_.borrow().h);
    }

    pub fn clear(self_: &crate::HxRefCell<IntMap<T>>) {
        self_.borrow_mut().h.clear();
    }
}
