// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod sys;
use crate::sys::Sys;

fn main() {
    return;
    println!("{}", String::from("nope"));
}
