// Generated by reflaxe.rust (POC)

// Haxe interface -> Rust trait

pub trait IMap<K: Clone + Send + Sync, V: Clone + Send + Sync>: Send + Sync {
    fn get(&self, k: K) -> Option<V>;
    fn set(&self, k: K, v: V) -> ();
    fn exists(&self, k: K) -> bool;
    fn remove(&self, k: K) -> bool;
    fn keys(&self) -> hxrt::iter::Iter<K>;
    fn iterator(&self) -> hxrt::iter::Iter<V>;
    fn key_value_iterator(&self) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>>;
    fn copy(&self) -> crate::HxRc<dyn crate::haxe_i_map::IMap<K, V> + Send + Sync>;
    fn to_string(&self) -> hxrt::string::HxString;
    fn clear(&self) -> ();
}
