// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn main() {
    let x: i32 = match hxrt::exception::catch_unwind(|| {
        hxrt::exception::throw(hxrt::dynamic::from(String::from("boom")));
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<String>() {
            Ok(_) => 2,
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
    println!("{}", x);
    let y: i32 = match hxrt::exception::catch_unwind(|| {
        match hxrt::exception::catch_unwind(|| {
            hxrt::exception::throw(hxrt::dynamic::from(7));
        }) {
            Ok(__hx_ok) => __hx_ok,
            Err(__hx_ex) => match __hx_ex.downcast::<i32>() {
                Ok(_) => hxrt::exception::throw(hxrt::dynamic::from(String::from("inner"))),
                Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
            },
        }
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<String>() {
            Ok(_) => 42,
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
    println!("{}", y);
}
