// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod sys;
use crate::sys::Sys;

fn main() {
    let mut x: i32 = match hxrt::exception::catch_unwind(|| {
        hxrt::exception::throw(hxrt::dynamic::from(String::from("boom")));
        1
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<String>() {
            Ok(__hx_box) => {
                let mut e: String = (*__hx_box);
                2
            }
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
    println!("{}", x);
    let mut y: i32 = match hxrt::exception::catch_unwind(|| {
        match hxrt::exception::catch_unwind(|| {
            hxrt::exception::throw(hxrt::dynamic::from(7));
            0
        }) {
            Ok(__hx_ok) => __hx_ok,
            Err(__hx_ex) => match __hx_ex.downcast::<i32>() {
                Ok(__hx_box) => {
                    let mut e: i32 = (*__hx_box);
                    hxrt::exception::throw(hxrt::dynamic::from(String::from("inner")))
                }
                Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
            },
        }
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<String>() {
            Ok(__hx_box) => {
                let mut e: String = (*__hx_box);
                42
            }
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
    println!("{}", y);
}
