// Generated by reflaxe.rust (POC)

use crate::HxRef;
use std::cell::RefCell;
use std::rc::Rc;

pub const __HX_TYPE_ID: u32 = 0x111fa3c1u32;

#[derive(Debug)]

pub struct Animal {}

impl Animal {
    pub fn new() -> HxRef<Animal> {
        let self_: HxRef<Animal> = Rc::new(RefCell::new(Animal {}));
        return self_;
    }
}

pub trait AnimalTrait: std::fmt::Debug {
    fn __hx_type_id(&self) -> u32;
}

impl crate::animal::AnimalTrait for RefCell<Animal> {
    fn __hx_type_id(&self) -> u32 {
        crate::animal::__HX_TYPE_ID
    }
}
