// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod animal;
mod dog;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let a: crate::HxRc<dyn crate::animal::AnimalTrait + Send + Sync> = crate::dog::Dog::new();
    println!("{}", hxrt::dynamic::from(true));
    println!(
        "{}",
        hxrt::dynamic::from(a.__hx_type_id() == crate::dog::__HX_TYPE_ID)
    );
}
