// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        _ => false,
    }
}

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3, 4, 5]);
    let s1: hxrt::array::Array<i32> = xs.slice(1, Some(4));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(s1.join(
        hxrt::string::HxString::from(hxrt::string::HxString::from(",")),
    ))));
    let removed: hxrt::array::Array<i32> = xs.splice(-2, 10);
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(
        removed.join(hxrt::string::HxString::from(hxrt::string::HxString::from(
            ",",
        ))),
    )));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(xs.join(
        hxrt::string::HxString::from(hxrt::string::HxString::from(",")),
    ))));
    let ys: hxrt::array::Array<i32> = xs.concat(hxrt::array::Array::<i32>::from_vec(vec![9, 10]));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(ys.join(
        hxrt::string::HxString::from(hxrt::string::HxString::from(",")),
    ))));
}
