// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod sys;

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![1, 2, 3, 4, 5]);
    let s1: hxrt::array::Array<i32> = xs.slice(1, Some(4));
    crate::sys::Sys::println(hxrt::dynamic::from(s1.join(String::from(",")).clone()));
    let removed: hxrt::array::Array<i32> = xs.splice(-2, 10);
    crate::sys::Sys::println(hxrt::dynamic::from(removed.join(String::from(",")).clone()));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from(",")).clone()));
    let ys: hxrt::array::Array<i32> = xs.concat(hxrt::array::Array::<i32>::from_vec(vec![9, 10]));
    crate::sys::Sys::println(hxrt::dynamic::from(ys.join(String::from(",")).clone()));
}
