// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x6002daa5u32;

#[derive(Debug)]

pub struct Dog {}

impl Dog {
    pub fn new() -> crate::HxRef<crate::dog::Dog> {
        let self_: crate::HxRef<crate::dog::Dog> = crate::HxRef::new(Dog {});
        return self_;
    }

    pub fn speak(_self_: &crate::HxRefCell<Dog>) -> hxrt::string::HxString {
        return hxrt::string::HxString::from(hxrt::string::HxString::from("dog"));
    }
}

impl crate::animal::AnimalTrait for crate::HxRefCell<Dog> {
    fn speak(&self) -> hxrt::string::HxString {
        Dog::speak(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::dog::__HX_TYPE_ID
    }
}
