// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x0d3c0cadu32;

#[derive(Debug)]

pub struct Date {
    ms: f64,
}

impl Date {
    pub fn new(
        year: i32,
        month: i32,
        day: i32,
        hour: i32,
        min: i32,
        sec: i32,
    ) -> crate::HxRef<crate::date::Date> {
        let self_: crate::HxRef<crate::date::Date> =
            crate::HxRc::new(crate::HxRefCell::new(Date { ms: 0.0 }));
        {
            let __tmp = hxrt::date::local_to_ms(year, month, day, hour, min, sec) as f64;
            self_.borrow_mut().ms = __tmp;
            __tmp
        };
        return self_;
    }

    pub fn get_time(self_: &crate::HxRefCell<Date>) -> f64 {
        return self_.borrow().ms;
    }

    pub fn get_hours(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_hours(self_.borrow().ms as i64);
    }

    pub fn get_minutes(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_minutes(self_.borrow().ms as i64);
    }

    pub fn get_seconds(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_seconds(self_.borrow().ms as i64);
    }

    pub fn get_full_year(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_full_year(self_.borrow().ms as i64);
    }

    pub fn get_month(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_month0(self_.borrow().ms as i64);
    }

    pub fn get_date(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_date(self_.borrow().ms as i64);
    }

    pub fn get_day(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::local_day(self_.borrow().ms as i64);
    }

    pub fn get_utc_hours(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_hours(self_.borrow().ms as i64);
    }

    pub fn get_utc_minutes(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_minutes(self_.borrow().ms as i64);
    }

    pub fn get_utc_seconds(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_seconds(self_.borrow().ms as i64);
    }

    pub fn get_utc_full_year(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_full_year(self_.borrow().ms as i64);
    }

    pub fn get_utc_month(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_month0(self_.borrow().ms as i64);
    }

    pub fn get_utc_date(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_date(self_.borrow().ms as i64);
    }

    pub fn get_utc_day(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::utc_day(self_.borrow().ms as i64);
    }

    pub fn get_timezone_offset(self_: &crate::HxRefCell<Date>) -> i32 {
        return hxrt::date::timezone_offset_minutes(self_.borrow().ms as i64);
    }

    pub fn to_string(self_: &crate::HxRefCell<Date>) -> String {
        return hxrt::date::format_local(self_.borrow().ms as i64);
    }

    pub fn now() -> crate::HxRef<crate::date::Date> {
        return crate::date::Date::from_time(hxrt::date::now_ms() as f64);
    }

    pub fn from_time(t: f64) -> crate::HxRef<crate::date::Date> {
        let d: crate::HxRef<crate::date::Date> = crate::date::Date::new(1970, 0, 1, 0, 0, 0);
        {
            let __tmp = t;
            d.borrow_mut().ms = __tmp;
            __tmp
        };
        return d;
    }

    pub fn from_string(s: String) -> crate::HxRef<crate::date::Date> {
        let t: f64 = hxrt::date::parse_to_ms(s.as_str()) as f64;
        return crate::date::Date::from_time(t);
    }
}
