// Generated by reflaxe.rust (POC)

use crate::HxRef;
use std::cell::RefCell;
use std::rc::Rc;

pub const __HX_TYPE_ID: u32 = 0x73f36c88u32;

#[derive(Debug)]

pub struct File {}

impl File {
    pub fn getContent(path: String) -> String {
        return std::fs::read_to_string(path.as_str()).unwrap();
    }

    pub fn saveContent(path: String, content: String) {
        {
            std::fs::write(path.as_str(), content).unwrap();
        };
    }

    pub fn getBytes(path: String) -> HxRef<hxrt::bytes::Bytes> {
        return {
            let data = std::fs::read(path.as_str()).unwrap();
            std::rc::Rc::new(std::cell::RefCell::new(hxrt::bytes::Bytes::from_vec(data)))
        };
    }

    pub fn saveBytes(path: String, bytes: HxRef<hxrt::bytes::Bytes>) {
        {
            std::fs::write(path.as_str(), bytes.borrow().as_slice()).unwrap();
        };
    }
}
