// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xaf52976eu32;

#[derive(Debug)]

pub struct BytesBuffer {
    chunks: hxrt::array::Array<crate::HxRef<hxrt::bytes::Bytes>>,
    finalized: bool,
    _length: i32,
}

impl BytesBuffer {
    pub fn new() -> crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> {
        let self_: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> =
            crate::HxRef::new(BytesBuffer {
                chunks: hxrt::array::Array::<crate::HxRef<hxrt::bytes::Bytes>>::new(),
                finalized: false,
                _length: 0,
            });
        return self_;
    }

    fn ensure_open(self_: &crate::HxRefCell<BytesBuffer>) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
    }

    pub fn get_length(self_: &crate::HxRefCell<BytesBuffer>) -> i32 {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._length
        };
    }

    pub fn add_byte(self_: &crate::HxRefCell<BytesBuffer>, byte: i32) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
        let b: crate::HxRef<hxrt::bytes::Bytes> =
            crate::HxRef::new(hxrt::bytes::Bytes::alloc(1 as usize));
        b.borrow_mut().set(0, byte);
        ({
            let __b = __hx_this.borrow();
            __b.chunks.clone()
        })
        .push(b.clone());
        {
            let __tmp = ({
                let __b = __hx_this.borrow();
                __b._length
            }) + 1;
            __hx_this.borrow_mut()._length = __tmp;
            __tmp
        };
    }

    pub fn add(self_: &crate::HxRefCell<BytesBuffer>, src: crate::HxRef<hxrt::bytes::Bytes>) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
        ({
            let __b = __hx_this.borrow();
            __b.chunks.clone()
        })
        .push(src.clone());
        {
            let __tmp = ({
                let __b = __hx_this.borrow();
                __b._length
            }) + src.borrow().length();
            __hx_this.borrow_mut()._length = __tmp;
            __tmp
        };
    }

    pub fn add_string(
        self_: &crate::HxRefCell<BytesBuffer>,
        v: hxrt::string::HxString,
        encoding: Option<crate::haxe_io_encoding::Encoding>,
    ) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
        crate::haxe_io_bytes_buffer::BytesBuffer::add(&*__hx_this, {
            let _ = encoding;
            crate::HxRef::new(hxrt::bytes::Bytes::of_string(v.as_str()))
        });
    }

    pub fn add_int32(self_: &crate::HxRefCell<BytesBuffer>, v: i32) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(&*__hx_this, v & 255);
        crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(&*__hx_this, v >> 8 & 255);
        crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(&*__hx_this, v >> 16 & 255);
        crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(
            &*__hx_this,
            (v as u32 >> 24 as u32) as i32,
        );
    }

    pub fn add_int64(
        self_: &crate::HxRefCell<BytesBuffer>,
        v: crate::HxRef<crate::haxe_int64_int64::Int64>,
    ) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        crate::haxe_io_bytes_buffer::BytesBuffer::add_int32(&*__hx_this, {
            let __b = v.borrow();
            __b.low
        });
        crate::haxe_io_bytes_buffer::BytesBuffer::add_int32(&*__hx_this, {
            let __b = v.borrow();
            __b.high
        });
    }

    pub fn add_float(self_: &crate::HxRefCell<BytesBuffer>, v: f64) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        crate::haxe_io_bytes_buffer::BytesBuffer::add_int32(
            &*__hx_this,
            crate::haxe_io_fp_helper::FPHelper::float_to_i32(v),
        );
    }

    pub fn add_double(self_: &crate::HxRefCell<BytesBuffer>, v: f64) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        crate::haxe_io_bytes_buffer::BytesBuffer::add_int64(
            &*__hx_this,
            crate::haxe_io_fp_helper::FPHelper::double_to_i64(v),
        );
    }

    pub fn add_bytes(
        self_: &crate::HxRefCell<BytesBuffer>,
        src: crate::HxRef<hxrt::bytes::Bytes>,
        pos: i32,
        len: i32,
    ) {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
        crate::haxe_io_bytes_buffer::BytesBuffer::add(
            &*__hx_this,
            crate::HxRef::new(src.borrow().sub(pos, len)),
        );
    }

    pub fn get_bytes(self_: &crate::HxRefCell<BytesBuffer>) -> crate::HxRef<hxrt::bytes::Bytes> {
        let __hx_this: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> = self_.self_ref();
        if {
            let __b = __hx_this.borrow();
            __b.finalized
        } {
            hxrt::exception::throw(hxrt::dynamic::from(hxrt::io::Error::Custom(
                hxrt::dynamic::from(hxrt::string::HxString::from("BytesBuffer is finalized")),
            )));
        }
        let out: crate::HxRef<hxrt::bytes::Bytes> = crate::HxRef::new(hxrt::bytes::Bytes::alloc(
            ({
                let __b = __hx_this.borrow();
                __b._length
            }) as usize,
        ));
        let mut offset: i32 = 0;
        {
            let mut _g: i32 = 0;
            let _g1: hxrt::array::Array<crate::HxRef<hxrt::bytes::Bytes>> = {
                let __b = __hx_this.borrow();
                __b.chunks.clone()
            };
            while _g < (_g1.len() as i32) {
                let chunk: crate::HxRef<hxrt::bytes::Bytes> = _g1.get_unchecked(_g as usize);
                {
                    _g = _g + 1;
                    _g
                };
                let n: i32 = chunk.borrow().length();
                hxrt::bytes::blit(&out, offset, &chunk, 0, n);
                offset = offset + n;
            }
        }
        {
            let __tmp = true;
            __hx_this.borrow_mut().finalized = __tmp;
            __tmp
        };
        {
            let __tmp = hxrt::array::Array::<crate::HxRef<hxrt::bytes::Bytes>>::new();
            __hx_this.borrow_mut().chunks = __tmp.clone();
            __tmp
        };
        return out;
    }
}
