// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let bb: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> =
        crate::haxe_io_bytes_buffer::BytesBuffer::new();
    crate::haxe_io_bytes_buffer::BytesBuffer::add_string(&bb, String::from("Hi"), None);
    crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(&bb, 32);
    crate::haxe_io_bytes_buffer::BytesBuffer::add_string(&bb, String::from("Rust"), None);
    crate::haxe_io_bytes_buffer::BytesBuffer::add_byte(&bb, 33);
    crate::sys::Sys::println(hxrt::dynamic::from(
        crate::haxe_io_bytes_buffer::BytesBuffer::get_length(&bb),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(
        crate::haxe_io_bytes_buffer::BytesBuffer::get_bytes(&bb)
            .borrow()
            .to_string()
            .clone(),
    ));
    let bb2: crate::HxRef<crate::haxe_io_bytes_buffer::BytesBuffer> =
        crate::haxe_io_bytes_buffer::BytesBuffer::new();
    match hxrt::exception::catch_unwind(|| {
        crate::haxe_io_bytes_buffer::BytesBuffer::add_bytes(
            &bb2,
            crate::HxRc::new(crate::HxRefCell::new(hxrt::bytes::Bytes::of_string(
                String::from("abc").as_str(),
            ))),
            0,
            999,
        );
        crate::sys::Sys::println(hxrt::dynamic::from(String::from("nope")));
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<hxrt::io::Error>() {
            Ok(__hx_box) => {
                let e: hxrt::io::Error = *__hx_box;
                crate::sys::Sys::println(hxrt::dynamic::from(
                    hxrt::dynamic::from(e.clone()).to_haxe_string().clone(),
                ));
            }
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
}
