// Generated by reflaxe.rust (POC)

use std::cell::RefCell;
use std::rc::Rc;

type HxRef<T> = Rc<RefCell<T>>;

mod sys;
use crate::sys::Sys;

fn main() {
    let mut xs: Vec<i32> = vec![1, 2, 3];
    let mut sum: i32 = 0;
    {
        let mut _g: i32 = 0;
        while (_g < (xs.len() as i32)) {
            let mut x: i32 = xs[(_g as usize)];
            {
                _g = (_g + 1);
                _g
            };
            sum = (sum + x);
        }
    };
    println!("{}", sum);
}
