// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x0cd85f36u32;

#[derive(Debug)]

pub struct EnumValueMap<
    K: Clone + Send + Sync + 'static + std::fmt::Debug,
    V: Clone + Send + Sync + 'static + std::fmt::Debug,
> {
    pub keys_map: std::collections::HashMap<String, K>,
    pub values_map: std::collections::HashMap<String, V>,
}

impl<
        K: Clone + Send + Sync + 'static + std::fmt::Debug,
        V: Clone + Send + Sync + 'static + std::fmt::Debug,
    > EnumValueMap<K, V>
{
    pub fn new() -> crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> {
        let self_: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            crate::HxRef::new(EnumValueMap {
                keys_map: std::collections::HashMap::<String, K>::new(),
                values_map: std::collections::HashMap::<String, V>::new(),
            });
        return self_;
    }

    pub fn set(self_: &crate::HxRefCell<EnumValueMap<K, V>>, key: K, value: V) {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        let id: String = format!("{:?}", key);
        crate::map_storage_tools::MapStorageTools::enumValueMapSet(
            __hx_this.clone(),
            id,
            key,
            value,
        );
    }

    pub fn get(self_: &crate::HxRefCell<EnumValueMap<K, V>>, key: K) -> Option<V> {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        let id: String = format!("{:?}", key);
        return crate::map_storage_tools::MapStorageTools::enumValueMapGetCloned(
            __hx_this.clone(),
            id,
        );
    }

    pub fn exists(self_: &crate::HxRefCell<EnumValueMap<K, V>>, key: K) -> bool {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        let id: String = format!("{:?}", key);
        return crate::map_storage_tools::MapStorageTools::enumValueMapExists(
            __hx_this.clone(),
            id,
        );
    }

    pub fn remove(self_: &crate::HxRefCell<EnumValueMap<K, V>>, key: K) -> bool {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        let id: String = format!("{:?}", key);
        return crate::map_storage_tools::MapStorageTools::enumValueMapRemoveExists(
            __hx_this.clone(),
            id,
        );
    }

    pub fn keys(self_: &crate::HxRefCell<EnumValueMap<K, V>>) -> hxrt::iter::Iter<K> {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        return crate::map_storage_tools::MapStorageTools::enumValueMapKeysOwned(__hx_this.clone());
    }

    pub fn iterator(self_: &crate::HxRefCell<EnumValueMap<K, V>>) -> hxrt::iter::Iter<V> {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        return crate::map_storage_tools::MapStorageTools::enumValueMapValuesOwned(
            __hx_this.clone(),
        );
    }

    pub fn key_value_iterator(
        self_: &crate::HxRefCell<EnumValueMap<K, V>>,
    ) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>> {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        return crate::map_storage_tools::MapStorageTools::enumValueMapKeyValuesOwned(
            __hx_this.clone(),
        );
    }

    pub fn copy(
        self_: &crate::HxRefCell<EnumValueMap<K, V>>,
    ) -> crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        let out: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            crate::haxe_ds_enum_value_map::EnumValueMap::<K, V>::new();
        crate::map_storage_tools::MapStorageTools::enumValueMapCloneInto(
            out.clone(),
            __hx_this.clone(),
        );
        return out;
    }

    pub fn to_string(self_: &crate::HxRefCell<EnumValueMap<K, V>>) -> String {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        return crate::map_storage_tools::MapStorageTools::enumValueMapDebugString(
            __hx_this.clone(),
        );
    }

    pub fn clear(self_: &crate::HxRefCell<EnumValueMap<K, V>>) {
        let __hx_this: crate::HxRef<crate::haxe_ds_enum_value_map::EnumValueMap<K, V>> =
            self_.self_ref();
        crate::map_storage_tools::MapStorageTools::enumValueMapClear(__hx_this.clone());
    }
}

impl<
        K: Clone + Send + Sync + 'static + std::fmt::Debug,
        V: Clone + Send + Sync + 'static + std::fmt::Debug,
    > crate::haxe_i_map::IMap<K, V> for crate::HxRefCell<EnumValueMap<K, V>>
{
    fn get(&self, k: K) -> Option<V> {
        EnumValueMap::<K, V>::get(self, k)
    }
    fn set(&self, k: K, v: V) -> () {
        EnumValueMap::<K, V>::set(self, k, v)
    }
    fn exists(&self, k: K) -> bool {
        EnumValueMap::<K, V>::exists(self, k)
    }
    fn remove(&self, k: K) -> bool {
        EnumValueMap::<K, V>::remove(self, k)
    }
    fn keys(&self) -> hxrt::iter::Iter<K> {
        EnumValueMap::<K, V>::keys(self)
    }
    fn iterator(&self) -> hxrt::iter::Iter<V> {
        EnumValueMap::<K, V>::iterator(self)
    }
    fn key_value_iterator(&self) -> hxrt::iter::Iter<hxrt::iter::KeyValue<K, V>> {
        EnumValueMap::<K, V>::key_value_iterator(self)
    }
    fn copy(&self) -> crate::HxRc<dyn crate::haxe_i_map::IMap<K, V> + Send + Sync> {
        let __tmp = EnumValueMap::<K, V>::copy(self);
        let __up: crate::HxRc<dyn crate::haxe_i_map::IMap<K, V> + Send + Sync> =
            match __tmp.as_arc_opt() {
                Some(__rc) => __rc.clone(),
                None => hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access"))),
            };
        __up
    }
    fn to_string(&self) -> String {
        EnumValueMap::<K, V>::to_string(self)
    }
    fn clear(&self) -> () {
        EnumValueMap::<K, V>::clear(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::haxe_ds_enum_value_map::__HX_TYPE_ID
    }
}
