// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x77d461c9u32;

#[derive(Debug)]

pub struct B {
    _x: i32,
}

impl B {
    pub fn new() -> crate::HxRef<crate::b::B> {
        let self_: crate::HxRef<crate::b::B> = crate::HxRef::new(B { _x: 0 });
        {
            let __tmp = 1;
            self_.borrow_mut()._x = __tmp;
            __tmp
        };
        return self_;
    }

    pub fn get_x(self_: &crate::HxRefCell<B>) -> i32 {
        let __hx_this: crate::HxRef<crate::b::B> = self_.self_ref();
        return crate::b::B::__hx_super_a_get_x(&*self_) + 10;
    }

    pub fn set_x(self_: &crate::HxRefCell<B>, v: i32) -> i32 {
        let __hx_this: crate::HxRef<crate::b::B> = self_.self_ref();
        return crate::b::B::__hx_super_a_set_x(&*self_, v + 10);
    }

    pub fn sound(_self_: &crate::HxRefCell<B>) -> String {
        return String::from("B.sound");
    }

    pub fn foo(_self_: &crate::HxRefCell<B>) -> String {
        return String::from("A.foo");
    }

    fn __hx_super_a_get_x(self_: &crate::HxRefCell<B>) -> i32 {
        let __hx_this: crate::HxRef<crate::b::B> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._x
        };
    }

    fn __hx_super_a_set_x(self_: &crate::HxRefCell<B>, v: i32) -> i32 {
        let __hx_this: crate::HxRef<crate::b::B> = self_.self_ref();
        {
            let __tmp = v;
            __hx_this.borrow_mut()._x = __tmp;
            __tmp
        };
        return v;
    }
}

pub trait BTrait: Send + Sync {
    fn __hx_get_u1_x(&self) -> i32;
    fn __hx_set_u1_x(&self, v: i32);
    fn get_x(&self) -> i32;
    fn set_x(&self, v: i32) -> i32;
    fn sound(&self) -> String;
    fn foo(&self) -> String;
    fn __hx_type_id(&self) -> u32;
}

impl crate::b::BTrait for crate::HxRefCell<B> {
    fn __hx_get_u1_x(&self) -> i32 {
        self.borrow()._x
    }
    fn __hx_set_u1_x(&self, v: i32) {
        self.borrow_mut()._x = v;
    }
    fn get_x(&self) -> i32 {
        B::get_x(self)
    }
    fn set_x(&self, v: i32) -> i32 {
        B::set_x(self, v)
    }
    fn sound(&self) -> String {
        B::sound(self)
    }
    fn foo(&self) -> String {
        B::foo(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::b::__HX_TYPE_ID
    }
}

impl crate::a::ATrait for crate::HxRefCell<B> {
    fn __hx_get_u1_x(&self) -> i32 {
        self.borrow()._x
    }
    fn __hx_set_u1_x(&self, v: i32) {
        self.borrow_mut()._x = v;
    }
    fn foo(&self) -> String {
        B::foo(self)
    }
    fn get_x(&self) -> i32 {
        B::get_x(self)
    }
    fn set_x(&self, v: i32) -> i32 {
        B::set_x(self, v)
    }
    fn sound(&self) -> String {
        B::sound(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::b::__HX_TYPE_ID
    }
}
