// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x76d46036u32;

#[derive(Debug)]

pub struct C {
    _x: i32,
}

impl C {
    pub fn new() -> crate::HxRef<crate::c::C> {
        let self_: crate::HxRef<crate::c::C> =
            std::rc::Rc::new(std::cell::RefCell::new(C { _x: 0 }));
        {
            let __tmp = 1;
            self_.borrow_mut()._x = __tmp;
            __tmp
        };
        return self_;
    }

    pub fn get_x(self_: &std::cell::RefCell<C>) -> i32 {
        return crate::c::C::__hx_super_b_get_x(&self_) + 100;
    }

    pub fn set_x(self_: &std::cell::RefCell<C>, v: i32) -> i32 {
        return crate::c::C::__hx_super_b_set_x(&self_, v + 100);
    }

    pub fn sound(_self_: &std::cell::RefCell<C>) -> String {
        return String::from("C.sound");
    }

    pub fn call_super_sound(self_: &std::cell::RefCell<C>) -> String {
        return crate::c::C::__hx_super_b_sound(&self_);
    }

    pub fn call_super_foo(self_: &std::cell::RefCell<C>) -> String {
        return crate::c::C::__hx_super_a_foo(&self_);
    }

    pub fn inc_super_x(self_: &std::cell::RefCell<C>) -> i32 {
        crate::c::C::__hx_super_b_set_x(&self_, crate::c::C::__hx_super_b_get_x(&self_) + 1);
        return crate::c::C::__hx_super_b_get_x(&self_);
    }

    pub fn foo(_self_: &std::cell::RefCell<C>) -> String {
        return String::from("A.foo");
    }

    fn __hx_super_a_foo(_self_: &std::cell::RefCell<C>) -> String {
        return String::from("A.foo");
    }

    fn __hx_super_b_get_x(self_: &std::cell::RefCell<C>) -> i32 {
        return crate::c::C::__hx_super_a_get_x(&self_) + 10;
    }

    fn __hx_super_b_set_x(self_: &std::cell::RefCell<C>, v: i32) -> i32 {
        return crate::c::C::__hx_super_a_set_x(&self_, v + 10);
    }

    fn __hx_super_b_sound(_self_: &std::cell::RefCell<C>) -> String {
        return String::from("B.sound");
    }

    fn __hx_super_a_get_x(self_: &std::cell::RefCell<C>) -> i32 {
        return self_.borrow()._x;
    }

    fn __hx_super_a_set_x(self_: &std::cell::RefCell<C>, v: i32) -> i32 {
        {
            let __tmp = v;
            self_.borrow_mut()._x = __tmp;
            __tmp
        };
        return v;
    }
}

impl crate::b::BTrait for std::cell::RefCell<C> {
    fn __hx_get_u1_x(&self) -> i32 {
        self.borrow()._x
    }
    fn __hx_set_u1_x(&self, v: i32) {
        self.borrow_mut()._x = v;
    }
    fn foo(&self) -> String {
        C::foo(self)
    }
    fn get_x(&self) -> i32 {
        C::get_x(self)
    }
    fn set_x(&self, v: i32) -> i32 {
        C::set_x(self, v)
    }
    fn sound(&self) -> String {
        C::sound(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::c::__HX_TYPE_ID
    }
}

impl crate::a::ATrait for std::cell::RefCell<C> {
    fn __hx_get_u1_x(&self) -> i32 {
        self.borrow()._x
    }
    fn __hx_set_u1_x(&self, v: i32) {
        self.borrow_mut()._x = v;
    }
    fn foo(&self) -> String {
        C::foo(self)
    }
    fn get_x(&self) -> i32 {
        C::get_x(self)
    }
    fn set_x(&self, v: i32) -> i32 {
        C::set_x(self, v)
    }
    fn sound(&self) -> String {
        C::sound(self)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::c::__HX_TYPE_ID
    }
}
