// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = std::rc::Rc<T>;
type HxRefCell<T> = std::cell::RefCell<T>;
type HxRef<T> = HxRc<HxRefCell<T>>;

mod rust_borrow;
mod rust_slice_tools;
mod sys;

fn main() {
    let mut v: Vec<i32> = Vec::<i32>::new();
    v.push(1);
    v.push(2);
    let mut sum: i32 = 0;
    for x in v.iter().copied() {
        sum = sum + x;
    }
    let mut sum2: i32 = 0;
    {
        let r: &Vec<i32> = &v;
        {
            let s: &[i32] = r;
            for y in s.iter().copied() {
                sum2 = sum2 + y;
            }
        }
    }
    println!("{}", hxrt::dynamic::from(sum + sum2));
}
