// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xd7cb7b80u32;

#[derive(Clone, Debug, PartialEq)]
pub enum StackItem {
    CFunction,
    Module(String),
    FilePos(Option<Box<StackItem>>, String, i32, Option<i32>),
    Method(Option<String>, String),
    LocalFunction(Option<i32>),
}
