// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0x9b8d53fbu32;

#[derive(Debug)]

pub struct Json {}

impl Json {
    pub fn parse(text: String) -> hxrt::dynamic::Dynamic {
        return hxrt::json::parse(text.as_str());
    }

    pub fn stringify(
        value: hxrt::dynamic::Dynamic,
        replacer: crate::HxDynRef<
            dyn Fn(hxrt::dynamic::Dynamic, hxrt::dynamic::Dynamic) -> hxrt::dynamic::Dynamic
                + Send
                + Sync,
        >,
        space: Option<String>,
    ) -> String {
        if !replacer.is_null() {
            hxrt::exception::throw(hxrt::dynamic::from(String::from(
                "haxe.Json.stringify: replacer is not supported on the Rust target yet",
            )));
        }
        return hxrt::json::stringify(&value, space.as_deref());
    }
}
