// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xad5d98ceu32;

#[derive(Debug)]

pub struct Exception {
    _message: String,
    _previous: crate::HxRef<crate::haxe_exception::Exception>,
    _native: hxrt::dynamic::Dynamic,
    _stack: hxrt::array::Array<crate::haxe_stack_item::StackItem>,
}

impl Exception {
    pub fn new(
        message: String,
        previous: crate::HxRef<crate::haxe_exception::Exception>,
        native: hxrt::dynamic::Dynamic,
    ) -> crate::HxRef<crate::haxe_exception::Exception> {
        let self_: crate::HxRef<crate::haxe_exception::Exception> = crate::HxRef::new(Exception {
            _message: message,
            _previous: previous,
            _native: native,
            _stack: hxrt::array::Array::<crate::haxe_stack_item::StackItem>::new(),
        });
        return self_;
    }

    pub fn get_message(self_: &crate::HxRefCell<Exception>) -> String {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._message.clone()
        };
    }

    pub fn get_stack(
        self_: &crate::HxRefCell<Exception>,
    ) -> hxrt::array::Array<crate::haxe_stack_item::StackItem> {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._stack.clone()
        };
    }

    pub fn get_previous(
        self_: &crate::HxRefCell<Exception>,
    ) -> crate::HxRef<crate::haxe_exception::Exception> {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._previous.clone()
        };
    }

    pub fn get_native(self_: &crate::HxRefCell<Exception>) -> hxrt::dynamic::Dynamic {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._native.clone()
        };
    }

    fn unwrap(self_: &crate::HxRefCell<Exception>) -> hxrt::dynamic::Dynamic {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._native.clone()
        };
    }

    pub fn to_string(self_: &crate::HxRefCell<Exception>) -> String {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return {
            let __b = __hx_this.borrow();
            __b._message.clone()
        };
    }

    pub fn details(self_: &crate::HxRefCell<Exception>) -> String {
        let __hx_this: crate::HxRef<crate::haxe_exception::Exception> = self_.self_ref();
        return format!(
            "{}{}{}",
            "Exception: ",
            crate::haxe_exception::Exception::to_string(&*__hx_this),
            crate::haxe_call_stack_call_stack_impl_::CallStackImpl::to_string(
                crate::haxe_exception::Exception::get_stack(&*__hx_this)
            )
        );
    }

    fn caught(value: hxrt::dynamic::Dynamic) -> crate::HxRef<crate::haxe_exception::Exception> {
        return crate::haxe_exception::Exception::new(
            String::from("Exception"),
            crate::HxRef::<crate::haxe_exception::Exception>::null(),
            value.clone(),
        );
    }

    fn thrown(value: hxrt::dynamic::Dynamic) -> hxrt::dynamic::Dynamic {
        return value;
    }
}
