// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod date;
mod haxe_call_stack_call_stack_impl_;
mod haxe_crypto_base64;
mod haxe_crypto_base_code;
mod haxe_crypto_sha256;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_list;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_json;
mod haxe_serializer;
mod haxe_stack_item;
mod haxe_unserializer;
mod haxe_unserializer_default_resolver;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;
mod value_type;

fn main() {
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "sha256=",
        crate::haxe_crypto_sha256::Sha256::encode(hxrt::string::HxString::from(
            hxrt::string::HxString::from("hello")
        ))
    ))));
    let b: crate::HxRef<hxrt::bytes::Bytes> = crate::HxRef::new(hxrt::bytes::Bytes::of_string(
        hxrt::string::HxString::from("hi").as_str(),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "b64=",
        crate::haxe_crypto_base64::Base64::encode(b.clone(), true)
    ))));
    let obj: crate::HxRef<hxrt::anon::Anon> = {
        let __o = crate::HxRef::new(hxrt::anon::Anon::new());
        {
            let mut __b = __o.borrow_mut();
            __b.set("a", 1);
            __b.set("b", hxrt::string::HxString::from("x"));
        };
        __o
    };
    let json: hxrt::string::HxString =
        hxrt::string::HxString::from(crate::haxe_json::Json::stringify(
            hxrt::dynamic::from_ref(obj.clone()),
            crate::HxDynRef::<
                dyn Fn(hxrt::dynamic::Dynamic, hxrt::dynamic::Dynamic) -> hxrt::dynamic::Dynamic
                    + Send
                    + Sync,
            >::null(),
            hxrt::string::HxString::from(hxrt::string::HxString::null()),
        ));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "json=", &json
    ))));
    let parsed: hxrt::dynamic::Dynamic =
        crate::haxe_json::Json::parse(hxrt::string::HxString::from(json.clone()));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "parsed.a=",
        hxrt::string::HxString::from(
            ({
                let __obj = parsed;
                hxrt::dynamic::field_get(&__obj, "a")
            })
            .to_haxe_string()
        )
    ))));
    let ser: hxrt::string::HxString = hxrt::string::HxString::from(
        crate::haxe_serializer::Serializer::run(hxrt::dynamic::from_ref(obj.clone())),
    );
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "ser=", &ser
    ))));
    let unser: hxrt::dynamic::Dynamic =
        crate::haxe_unserializer::Unserializer::run(hxrt::string::HxString::from(ser.clone()));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "unser.b=",
        hxrt::string::HxString::from(
            ({
                let __obj = unser;
                hxrt::dynamic::field_get(&__obj, "b")
            })
            .to_haxe_string()
        )
    ))));
}
