// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xb78f52beu32;

#[derive(Clone, Debug, PartialEq)]
pub enum ValueType {
    TNull,
    TInt,
    TFloat,
    TBool,
    TObject,
    TFunction,
    TClass(u32),
    TEnum(u32),
    TUnknown,
}
