// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod db_sqlite_driver;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_list;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_db_connection;
mod sys_db_result_set;
mod sys_db_sqlite;
mod sys_db_sqlite_sqlite_connection;
mod sys_db_sqlite_sqlite_result_set;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let cnx: crate::HxRc<dyn crate::sys_db_connection::Connection + Send + Sync> =
        crate::sys_db_sqlite::Sqlite::open(String::from(":memory:"));
    cnx.request(String::from("CREATE TABLE todo (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, done INTEGER NOT NULL)"));
    cnx.request(format!(
        "{}{}{}",
        "INSERT INTO todo (name, done) VALUES (",
        cnx.quote(String::from("bootstrap reflaxe.rust")),
        ", 1)"
    ));
    cnx.request(format!(
        "{}{}{}",
        "INSERT INTO todo (name, done) VALUES (",
        cnx.quote(String::from("ship sys.db sqlite")),
        ", 0)"
    ));
    let rs: crate::HxRc<dyn crate::sys_db_result_set::ResultSet + Send + Sync> =
        cnx.request(String::from("SELECT id, name, done FROM todo ORDER BY id"));
    let fields: hxrt::array::Array<String> = rs.get_fields_names();
    crate::sys::Sys::println(hxrt::dynamic::from(format!("{}{}", "db=", cnx.db_name())));
    crate::sys::Sys::println(hxrt::dynamic::from(format!(
        "{}{}",
        "fields=",
        if fields.is_null() {
            String::from("null")
        } else {
            fields.join(String::from(","))
        }
    )));
    crate::sys::Sys::println(hxrt::dynamic::from(format!(
        "{}{}{}{}",
        "len0=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " nf=",
        hxrt::dynamic::from(rs.get_nfields()).to_haxe_string()
    )));
    let r1: hxrt::dynamic::Dynamic = rs.next();
    crate::sys::Sys::println(hxrt::dynamic::from(format!(
        "{}{}{}{}{}{}{}{}{}{}",
        "len1=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " row1=",
        hxrt::dynamic::field_get(&r1, "id").to_haxe_string(),
        ",",
        hxrt::dynamic::field_get(&r1, "name").to_haxe_string(),
        ",",
        hxrt::dynamic::field_get(&r1, "done").to_haxe_string(),
        " get0=",
        hxrt::dynamic::from(rs.get_int_result(0)).to_haxe_string()
    )));
    let r2: hxrt::dynamic::Dynamic = rs.next();
    crate::sys::Sys::println(hxrt::dynamic::from(format!(
        "{}{}{}{}{}{}{}{}{}{}",
        "len2=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " row2=",
        hxrt::dynamic::field_get(&r2, "id").to_haxe_string(),
        ",",
        hxrt::dynamic::field_get(&r2, "name").to_haxe_string(),
        ",",
        hxrt::dynamic::field_get(&r2, "done").to_haxe_string(),
        " get1=",
        rs.get_result(1)
    )));
    let r3: hxrt::dynamic::Dynamic = rs.next();
    crate::sys::Sys::println(hxrt::dynamic::from(format!(
        "{}{}",
        "end=",
        r3.is_null().to_string()
    )));
}
