// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod db_sqlite_driver;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_list;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_db_connection;
mod sys_db_result_set;
mod sys_db_sqlite;
mod sys_db_sqlite_sqlite_connection;
mod sys_db_sqlite_sqlite_result_set;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => matches!(expected, 0x44f4c432u32),
        0x39e0cd5bu32 => matches!(expected, 0x44f4c432u32),
        0xd7e07825u32 => matches!(expected, 0x44f4c432u32),
        0x181f937bu32 => matches!(expected, 0x44f4c432u32),
        0x905152c9u32 => matches!(expected, 0xf061f824u32),
        0xedbd9a5cu32 => matches!(expected, 0x0d10401bu32),
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        _ => false,
    }
}

fn main() {
    let cnx: crate::HxRc<dyn crate::sys_db_connection::Connection + Send + Sync> =
        crate::sys_db_sqlite::Sqlite::open(hxrt::string::HxString::from(
            hxrt::string::HxString::from(":memory:"),
        ));
    cnx.request(hxrt::string::HxString::from(hxrt::string::HxString::from("CREATE TABLE todo (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, done INTEGER NOT NULL)")));
    cnx.request(hxrt::string::HxString::from(hxrt::string::HxString::from(
        format!(
            "{}{}{}",
            "INSERT INTO todo (name, done) VALUES (",
            cnx.quote(hxrt::string::HxString::from(hxrt::string::HxString::from(
                "bootstrap reflaxe.rust"
            ))),
            ", 1)"
        ),
    )));
    cnx.request(hxrt::string::HxString::from(hxrt::string::HxString::from(
        format!(
            "{}{}{}",
            "INSERT INTO todo (name, done) VALUES (",
            cnx.quote(hxrt::string::HxString::from(hxrt::string::HxString::from(
                "ship sys.db sqlite"
            ))),
            ", 0)"
        ),
    )));
    let rs: crate::HxRc<dyn crate::sys_db_result_set::ResultSet + Send + Sync> =
        cnx.request(hxrt::string::HxString::from(hxrt::string::HxString::from(
            "SELECT id, name, done FROM todo ORDER BY id",
        )));
    let fields: hxrt::array::Array<hxrt::string::HxString> = rs.get_fields_names();
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "db=",
        cnx.db_name()
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "fields=",
        if fields.is_null() {
            hxrt::string::HxString::from("null")
        } else {
            hxrt::string::HxString::from(fields.join(hxrt::string::HxString::from(
                hxrt::string::HxString::from(","),
            )))
        }
    ))));
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}{}{}",
        "len0=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " nf=",
        hxrt::dynamic::from(rs.get_nfields()).to_haxe_string()
    ))));
    let r1: crate::HxRef<hxrt::anon::Anon> = {
        let __hx_dyn = rs.next();
        if __hx_dyn.is_null() {
            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
        } else {
            __hx_dyn
                .downcast_ref::<crate::HxRef<hxrt::anon::Anon>>()
                .unwrap()
                .clone()
        }
    };
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}{}{}{}{}{}{}{}{}",
        "len1=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " row1=",
        hxrt::dynamic::from(r1.borrow().get::<i32>("id")).to_haxe_string(),
        ",",
        r1.borrow().get::<hxrt::string::HxString>("name"),
        ",",
        hxrt::dynamic::from(r1.borrow().get::<i32>("done")).to_haxe_string(),
        " get0=",
        hxrt::dynamic::from(rs.get_int_result(0)).to_haxe_string()
    ))));
    let r2: crate::HxRef<hxrt::anon::Anon> = {
        let __hx_dyn = rs.next();
        if __hx_dyn.is_null() {
            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
        } else {
            __hx_dyn
                .downcast_ref::<crate::HxRef<hxrt::anon::Anon>>()
                .unwrap()
                .clone()
        }
    };
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}{}{}{}{}{}{}{}{}",
        "len2=",
        hxrt::dynamic::from(rs.get_length()).to_haxe_string(),
        " row2=",
        hxrt::dynamic::from(r2.borrow().get::<i32>("id")).to_haxe_string(),
        ",",
        r2.borrow().get::<hxrt::string::HxString>("name"),
        ",",
        hxrt::dynamic::from(r2.borrow().get::<i32>("done")).to_haxe_string(),
        " get1=",
        rs.get_result(1)
    ))));
    let r3: crate::HxRef<hxrt::anon::Anon> = {
        let __hx_dyn = rs.next();
        if __hx_dyn.is_null() {
            hxrt::exception::throw(hxrt::dynamic::from(String::from("Null Access")))
        } else {
            __hx_dyn
                .downcast_ref::<crate::HxRef<hxrt::anon::Anon>>()
                .unwrap()
                .clone()
        }
    };
    crate::sys::Sys::println(hxrt::dynamic::from(hxrt::string::HxString::from(format!(
        "{}{}",
        "end=",
        hxrt::string::HxString::from(r3.is_null().to_string())
    ))));
}
