// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0x07f2cc68u32;

#[derive(Debug)]

pub struct Sqlite {}

impl Sqlite {
    pub fn open(
        file: hxrt::string::HxString,
    ) -> crate::HxRc<dyn crate::sys_db_connection::Connection + Send + Sync> {
        return {
            let __tmp = crate::sys_db_sqlite_sqlite_connection::SqliteConnection::new(
                hxrt::string::HxString::from(file),
            );
            let __up: crate::HxRc<dyn crate::sys_db_connection::Connection + Send + Sync> =
                __tmp.as_arc_opt().unwrap().clone();
            __up
        };
    }
}
