#!/usr/bin/env node

const assert = require('assert')
const cp = require('child_process')
const fs = require('fs')
const os = require('os')
const path = require('path')

const repoRoot = path.resolve(__dirname, '..', '..')
const haxeShim = path.join(repoRoot, 'node_modules', 'lix', 'bin', 'haxeshim.js')
const astPath = path.join(repoRoot, 'src', 'reflaxe', 'rust', 'ast', 'RustAST.hx')
const compilerPath = path.join(repoRoot, 'src', 'reflaxe', 'rust', 'RustCompiler.hx')
const pathAnalysisPath = path.join(repoRoot, 'src', 'reflaxe', 'rust', 'ast', 'RustPathAnalysis.hx')
const passDir = path.join(repoRoot, 'src', 'reflaxe', 'rust', 'passes')
const harnessPath = path.join(repoRoot, 'scripts', 'ci', 'harness.sh')

function runHaxe(args) {
  return cp.spawnSync(process.execPath, [haxeShim, ...args], {
    cwd: repoRoot,
    encoding: 'utf8'
  })
}

function output(result) {
  return `${result.stdout || ''}\n${result.stderr || ''}`
}

function compileLegacyFixture(root, name, source, expected) {
  const fixtureDir = path.join(root, name)
  fs.mkdirSync(fixtureDir, { recursive: true })
  fs.writeFileSync(path.join(fixtureDir, 'Main.hx'), source)
  const result = runHaxe(['-cp', 'src', '-cp', fixtureDir, '-main', 'Main', '--no-output'])
  assert.notStrictEqual(result.status, 0, `${name} must reject the obsolete item representation`)
  assert.match(output(result), expected, `${name} must identify the removed structural contract`)
}

function main() {
  assert.match(
    fs.readFileSync(harnessPath, 'utf8'),
    /structural Rust item contract" npm run test:rust-structural-items/,
    'the full harness must run the structural item contract'
  )

  const args = [
    '-cp', 'src',
    '-cp', 'test/compiler',
    '-main', 'RustStructuralItemContract',
    '--interp'
  ]
  const first = runHaxe(args)
  assert.strictEqual(first.status, 0, output(first))
  const second = runHaxe(args)
  assert.strictEqual(second.status, 0, output(second))
  assert.strictEqual(first.stdout, second.stdout, 'structural item printer bytes must be repeatable')
  assert.strictEqual(first.stderr, second.stderr, 'structural item diagnostics must be repeatable')

  const passArgs = [
    '-cp', 'src',
    '-cp', 'test/compiler',
    '--macro', 'RustStructuralItemPassContract.run()',
    '--no-output'
  ]
  const firstPass = runHaxe(passArgs)
  assert.strictEqual(firstPass.status, 0, output(firstPass))
  const secondPass = runHaxe(passArgs)
  assert.strictEqual(secondPass.status, 0, output(secondPass))
  assert.strictEqual(firstPass.stdout, secondPass.stdout,
    'recursive structural-item pass output must be repeatable')
  assert.strictEqual(firstPass.stderr, secondPass.stderr,
    'recursive structural-item pass diagnostics must be repeatable')

  const noHxrtArgs = [
    '-cp', 'src',
    '-cp', 'test/compiler',
    '--macro', 'RustStructuralItemPassContract.rejectNestedHxrt()',
    '--no-output'
  ]
  const firstNoHxrt = runHaxe(noHxrtArgs)
  assert.notStrictEqual(firstNoHxrt.status, 0,
    'rust_no_hxrt must reject runtime paths hidden inside structural nested items')
  const secondNoHxrt = runHaxe(noHxrtArgs)
  assert.notStrictEqual(secondNoHxrt.status, 0,
    'repeat rust_no_hxrt contract must remain fail-closed')
  assert.strictEqual(firstNoHxrt.stdout, secondNoHxrt.stdout,
    'nested no-hxrt output must be repeatable')
  assert.strictEqual(firstNoHxrt.stderr, secondNoHxrt.stderr,
    'nested no-hxrt diagnostics must be repeatable')
  const noHxrtOutput = output(firstNoHxrt)
  assert.match(noHxrtOutput, /HXRS-NO-HXRT-EMITTED-RUNTIME/,
    'the failure must come from the emitted-runtime no-hxrt policy')
  assert.match(noHxrtOutput, /references `hxrt` 8 time\(s\)/,
    'no-hxrt recursion must observe all eight independently placed runtime paths')
  for (const kind of ['attribute', 'inner attribute', 'use', 'type', 'path']) {
    assert.match(noHxrtOutput, new RegExp(kind + ' `hxrt::'),
      `no-hxrt diagnostic must include a structural ${kind} sample`)
  }

  const expected = [
    '// Generated by structural item contract',
    '',
    '#![allow(dead_code, unused_imports)]',
    '',
    'pub use core::fmt::Debug as FmtDebug;',
    '',
    'type Maybe<T> = Option<T>;',
    '',
    '/// Contract type id.',
    'pub const TYPE_ID: u32 = 0x80000001u32;',
    '',
    'static ENABLED: bool = true;',
    '',
    'const UNIT: () = ();',
    '',
    'mod external;',
    'pub mod support {',
    '    pub(crate) const VALUE: i32 = 7;',
    '}',
    'pub mod grouped {',
    '    pub use core::fmt::{Debug as DebugTrait, Display};',
    '}',
    'pub mod alias {',
    '    pub use crate::support::*;',
    '}',
    '',
    '#[cfg(test)]',
    'mod test_only {',
    '    #[test]',
    '    fn smoke() { }',
    '}',
    '',
    '#[derive(Clone, Debug)]',
    'pub struct Packet {',
    '    pub value: i32,',
    '}',
    ''
  ].join('\n')
  assert.strictEqual(first.stdout, expected)

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'haxe-rust-structural-items-'))
  try {
    const rustSourcePath = path.join(tempDir, 'contract.rs')
    fs.writeFileSync(rustSourcePath, first.stdout)
    fs.writeFileSync(path.join(tempDir, 'external.rs'), 'pub const EXTERNAL: i32 = 1;\n')
    const rustc = cp.spawnSync('rustc', [
      '--crate-name', 'structural_item_contract',
      '--crate-type', 'lib',
      '--edition', '2021',
      '-D', 'warnings',
      rustSourcePath,
      '-o', path.join(tempDir, 'libcontract.rlib')
    ], {cwd: tempDir, encoding: 'utf8'})
    assert.strictEqual(rustc.status, 0, output(rustc))

    compileLegacyFixture(tempDir, 'enum-derive-strings', `
import reflaxe.rust.ast.RustAST.RustEnum;
import reflaxe.rust.ast.RustAST.RustGenericParameters;
class Main {
  static function main():Void {
    var value:RustEnum = {
      name: "Legacy",
      isPub: false,
      generics: RustGenericParameters.empty(),
      derives: ["Clone"],
      variants: []
    };
    var legacy:Array<String> = value.derives;
  }
}
`, /derives/)

    compileLegacyFixture(tempDir, 'retired-raw-item-reason', `
import reflaxe.rust.ast.RustAST.RustCompilerRawReason;
class Main {
  static function main():Void {
    var reason:RustCompilerRawReason = RawGeneratedFileMarker;
  }
}
`, /RawGeneratedFileMarker/)
  } finally {
    fs.rmSync(tempDir, {recursive: true, force: true})
  }

  const ast = fs.readFileSync(astPath, 'utf8')
  for (const constructor of ['RAttributed', 'RInnerAttribute', 'RComment', 'RUse', 'RModule', 'RConst', 'RStatic', 'RTypeAlias']) {
    assert.match(ast, new RegExp(`\\b${constructor}\\(`), `RustItem must expose ${constructor}`)
  }
  assert.doesNotMatch(ast, /var derives:Array<String>/,
    'enum derives must use the common structural attribute/path representation')

  const compiler = fs.readFileSync(compilerPath, 'utf8')
  for (const rawReason of [
    'RawGeneratedFileMarker',
    'RawCrateHeader',
    'RawNestedModuleDeclarations',
    'RawBaseTraitImport',
    'RawTypeIdConstant',
    'RawDeriveAttribute',
    'RawGeneratedTestModule'
  ]) {
    assert.doesNotMatch(compiler, new RegExp(`\\b${rawReason}\\b`),
      `${rawReason} must have no compiler producer after structural item migration`)
  }
  assert.match(compiler, /RustMetadataSyntax\.parsePath\s*\(/,
    'rustDerive metadata must cross into structural paths exactly once at its source boundary')

  const pathAnalysis = fs.readFileSync(pathAnalysisPath, 'utf8')
  assert.match(pathAnalysis, /function visitAttributeTree\s*\(/,
    'attribute paths need one shared structural traversal authority')
  assert.match(pathAnalysis, /function visitUseTree\s*\(/,
    'use-tree paths need one shared structural traversal authority')

  const passSources = [
    'BorrowScopeTighteningPass.hx',
    'CloneElisionPass.hx',
    'MutInferencePass.hx',
    'StatementCleanupPass.hx'
  ].map(name => fs.readFileSync(path.join(passDir, name), 'utf8'))
  for (const passSource of passSources) {
    assert.match(passSource, /case RModule\s*\(/,
      'ownership and cleanup passes must recurse into inline module functions')
  }

  const passTools = fs.readFileSync(path.join(passDir, 'RustPassTools.hx'), 'utf8')
  assert.match(passTools, /case RModule\s*\(/,
    'shared pass traversal must recurse into inline modules')
  assert.match(passTools, /case RConst\s*\(/,
    'shared pass traversal must map constant initializers')
  assert.match(passTools, /case RStatic\s*\(/,
    'shared pass traversal must map static initializers')

  const normalizePass = fs.readFileSync(path.join(passDir, 'NormalizePass.hx'), 'utf8')
  assert.match(normalizePass, /case RModule\s*\(/,
    'raw normalization must recurse into inline modules')

  const noHxrtPass = fs.readFileSync(path.join(passDir, 'NoHxrtPass.hx'), 'utf8')
  assert.match(noHxrtPass, /RustPathAnalysis\.visitAttributeTree\s*\(/,
    'no-hxrt policy must scan structural attribute paths')
  assert.match(noHxrtPass, /RustPathAnalysis\.visitUseTree\s*\(/,
    'no-hxrt policy must scan structural use trees')
  assert.match(noHxrtPass, /case RConst\s*\(/,
    'no-hxrt policy must scan constant type and initializer paths')
  assert.match(noHxrtPass, /case RModule\s*\(/,
    'no-hxrt policy must recurse into nested modules')

  console.log('[rust-structural-items-test] OK')
}

main()
