// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod _meters_meters_impl_;
mod sys;

fn main() {
    let a: i32 = 5;
    let b: i32 = {
        let this1: i32;
        this1 = 2.8 as i32;
        this1 as i32
    };
    let c: i32 = {
        let this1_2: i32;
        this1_2 = a as i32 + b;
        this1_2 as i32
    };
    let as_int: i32 = c;
    println!("{}", hxrt::dynamic::from(as_int));
    let col: i32 = 1 as i32;
    let raw: i32 = col;
    println!("{}", hxrt::dynamic::from(raw));
    match col {
        1 => {
            println!("{}", hxrt::dynamic::from(String::from("r")));
        }
        2 => {
            println!("{}", hxrt::dynamic::from(String::from("g")));
        }
        3 => {
            println!("{}", hxrt::dynamic::from(String::from("b")));
        }
        _ => {
            println!("{}", hxrt::dynamic::from(String::from("?")));
        }
    }
}
