// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xb840ae5fu32;

#[derive(Debug)]

pub struct Counter {
    pub n: i32,
}

impl Counter {
    pub fn new(n: i32) -> crate::HxRef<crate::counter::Counter> {
        let self_: crate::HxRef<crate::counter::Counter> =
            std::rc::Rc::new(std::cell::RefCell::new(Counter { n: n }));
        return self_;
    }

    pub fn inc(self_: &std::cell::RefCell<Counter>) {
        {
            let __tmp = self_.borrow().n + 1;
            self_.borrow_mut().n = __tmp;
            __tmp
        };
    }
}
