// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod counter;
mod e;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let xs: hxrt::array::Array<i32> = hxrt::array::Array::<i32>::from_vec(vec![3, 1, 2]);
    xs.sort(crate::HxRc::new(move |a: i32, b: i32| {
        return a - b;
    }));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from(",")).clone()));
    let removed: hxrt::array::Array<i32> = xs.splice(1, 1);
    crate::sys::Sys::println(hxrt::dynamic::from(removed.join(String::from(",")).clone()));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.join(String::from(",")).clone()));
    let c: crate::HxRef<crate::counter::Counter> = crate::counter::Counter::new(0);
    crate::counter::Counter::inc(&c);
    crate::sys::Sys::println(hxrt::dynamic::from(c.borrow().n));
    let e: crate::e::E = crate::e::E::B(7);
    let msg: String = match e.clone() {
        crate::e::E::A => String::from("A"),
        crate::e::E::B(__p) => {
            let _g: i32 = __p;
            {
                let i: i32 = _g;
                format!("{}{}", "B:", hxrt::dynamic::from(i).to_haxe_string())
            }
        }
    };
    crate::sys::Sys::println(hxrt::dynamic::from(msg.clone()));
    let caught: String = match hxrt::exception::catch_unwind(|| {
        hxrt::exception::throw(hxrt::dynamic::from(String::from("boom")));
    }) {
        Ok(__hx_ok) => __hx_ok,
        Err(__hx_ex) => match __hx_ex.downcast::<String>() {
            Ok(_) => String::from("caught"),
            Err(__hx_ex) => hxrt::exception::rethrow(__hx_ex),
        },
    };
    crate::sys::Sys::println(hxrt::dynamic::from(caught.clone()));
    let f: crate::HxRc<dyn Fn(i32) -> i32 + Send + Sync> = crate::HxRc::new(move |x: i32| {
        return x + 1;
    });
    crate::sys::Sys::println(hxrt::dynamic::from(f(10)));
}
