// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xe26ae42cu32;

#[derive(Clone, Debug, PartialEq)]
pub enum NextEventTime {
    Now,
    Never,
    AnyTime(Option<f64>),
    At(f64),
}
