// Generated by reflaxe.rust

#![deny(warnings)]
#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod counter;
mod fp_helper;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int32_int32_impl_;
mod haxe_int64_helper;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_iterators_string_iterator;
mod haxe_iterators_string_key_value_iterator;
mod haxe_stack_item;
mod int32_tools;
mod map_storage_tools;
mod string_buf;
mod string_tools;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

/// Runtime subtype check for stable Haxe class type ids.
///
/// Generated by reflaxe.rust from the emitted class inheritance graph.
#[inline]
pub(crate) fn __hx_is_subtype_type_id(actual: u32, expected: u32) -> bool {
    if actual == expected {
        return true;
    }
    match actual {
        0x0cd85f36u32 => matches!(expected, 0x44f4c432u32),
        0x39e0cd5bu32 => matches!(expected, 0x44f4c432u32),
        0xd7e07825u32 => matches!(expected, 0x44f4c432u32),
        0x181f937bu32 => matches!(expected, 0x44f4c432u32),
        0x163b1f5au32 => matches!(expected, 0xe82620b4u32),
        0xfb16179cu32 => matches!(expected, 0xd50291cbu32),
        0x9402c169u32 => matches!(expected, 0xe82620b4u32),
        _ => false,
    }
}

fn main() {
    let channel: crate::HxRef<hxrt::concurrent::ChannelHandle<String>> =
        hxrt::concurrent::channel_new();
    let worker_channel: crate::HxRef<hxrt::concurrent::ChannelHandle<String>> = channel.clone();
    let task: crate::HxRef<hxrt::concurrent::TaskHandle<i32>> = hxrt::concurrent::task_spawn({
        let __rc: crate::HxRc<dyn Fn() -> i32 + Send + Sync> = crate::HxRc::new(move || {
            hxrt::concurrent::channel_send(&worker_channel, String::from("ping"));
            return 2;
        });
        crate::HxDynRef::new(__rc)
    });
    let received: String = hxrt::concurrent::channel_recv(&channel);
    let joined: i32 = hxrt::concurrent::task_join(&task);
    let mutex: crate::HxRef<hxrt::concurrent::MutexHandle<crate::HxRef<crate::counter::Counter>>> =
        hxrt::concurrent::mutex_new(crate::counter::Counter::new(1));
    let mutex_value: crate::HxRef<crate::counter::Counter> =
        hxrt::concurrent::mutex_update(&mutex, {
            let __rc: crate::HxRc<
                dyn Fn(
                        crate::HxRef<crate::counter::Counter>,
                    ) -> crate::HxRef<crate::counter::Counter>
                    + Send
                    + Sync,
            > = crate::HxRc::new(move |counter: crate::HxRef<crate::counter::Counter>| {
                {
                    let __tmp = ({
                        let __b = counter.borrow();
                        __b.value
                    }) + joined;
                    counter.borrow_mut().value = __tmp;
                    __tmp
                };
                return counter;
            });
            crate::HxDynRef::new(__rc)
        });
    let lock: crate::HxRef<hxrt::concurrent::RwLockHandle<crate::HxRef<crate::counter::Counter>>> =
        hxrt::concurrent::rw_lock_new(crate::counter::Counter::new(5));
    let before: crate::HxRef<crate::counter::Counter> = hxrt::concurrent::rw_lock_read(&lock);
    let after: crate::HxRef<crate::counter::Counter> = hxrt::concurrent::rw_lock_update(&lock, {
        let __rc: crate::HxRc<
            dyn Fn(crate::HxRef<crate::counter::Counter>) -> crate::HxRef<crate::counter::Counter>
                + Send
                + Sync,
        > = crate::HxRc::new(move |counter: crate::HxRef<crate::counter::Counter>| {
            {
                let __tmp = ({
                    let __b = counter.borrow();
                    __b.value
                }) + 4;
                counter.borrow_mut().value = __tmp;
                __tmp
            };
            return counter;
        });
        crate::HxDynRef::new(__rc)
    });
    let final_value: crate::HxRef<crate::counter::Counter> = hxrt::concurrent::rw_lock_read(&lock);
    let empty: bool = {
        let _g: Option<String> = hxrt::concurrent::channel_try_recv(&channel);
        match _g.clone() {
            Option::Some(__p) => {
                let _ = __p;
                false
            }
            Option::None => true,
        }
    };
    println!("{}", hxrt::dynamic::from(received));
    println!("{}", hxrt::dynamic::from(joined));
    println!(
        "{}",
        hxrt::dynamic::from({
            let __b = mutex_value.borrow();
            __b.value
        })
    );
    println!(
        "{}",
        hxrt::dynamic::from({
            let __b = before.borrow();
            __b.value
        })
    );
    println!(
        "{}",
        hxrt::dynamic::from({
            let __b = after.borrow();
            __b.value
        })
    );
    println!(
        "{}",
        hxrt::dynamic::from({
            let __b = final_value.borrow();
            __b.value
        })
    );
    println!("{}", hxrt::dynamic::from(empty));
}
