// Generated by reflaxe.rust

pub const __HX_TYPE_ID: u32 = 0xc5e84041u32;

#[derive(Debug)]
pub struct Payload {
    pub name: hxrt::string::HxString,
}

impl Payload {
    pub fn new(name: hxrt::string::HxString) -> crate::HxRef<crate::payload::Payload> {
        let self_: crate::HxRef<crate::payload::Payload> =
            crate::HxRef::new(Payload { name: name });
        return self_;
    }
}
