// Generated by reflaxe.rust (POC)

#![allow(dead_code)]
#![allow(type_alias_bounds)]

type HxRc<T> = hxrt::cell::HxRc<T>;
type HxDynRef<T: ?Sized> = hxrt::cell::HxDynRef<T>;
type HxRefCell<T> = hxrt::cell::HxCell<T>;
type HxRef<T> = hxrt::cell::HxRef<T>;

mod foo;
mod haxe_call_stack_call_stack_impl_;
mod haxe_ds_enum_value_map;
mod haxe_ds_int_map;
mod haxe_ds_object_map;
mod haxe_ds_string_map;
mod haxe_exception;
mod haxe_i_map;
mod haxe_int64_int64;
mod haxe_int64_int64_impl_;
mod haxe_io_bytes_buffer;
mod haxe_io_encoding;
mod haxe_io_eof;
mod haxe_io_fp_helper;
mod haxe_io_input;
mod haxe_io_output;
mod haxe_stack_item;
mod string_buf;
mod sys;
mod sys_io_stderr;
mod sys_io_stdin;
mod sys_io_stdout;

fn main() {
    let a: crate::HxRef<crate::foo::Foo> = crate::foo::Foo::new(1);
    let b: crate::HxRef<crate::foo::Foo> = crate::foo::Foo::new(1);
    let c: crate::HxRef<crate::foo::Foo> = a.clone();
    let xs: hxrt::array::Array<crate::HxRef<crate::foo::Foo>> =
        hxrt::array::Array::<crate::HxRef<crate::foo::Foo>>::from_vec(vec![a.clone(), b, c]);
    crate::sys::Sys::println(hxrt::dynamic::from(xs.containsRef(a.clone())));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.containsRef(crate::foo::Foo::new(1))));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.indexOfRef(a.clone(), None)));
    crate::sys::Sys::println(hxrt::dynamic::from(
        xs.indexOfRef(crate::foo::Foo::new(1), None),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.lastIndexOfRef(a.clone(), None)));
    crate::sys::Sys::println(hxrt::dynamic::from(
        xs.lastIndexOfRef(crate::foo::Foo::new(1), None),
    ));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.removeRef(crate::foo::Foo::new(1))));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.removeRef(a.clone())));
    crate::sys::Sys::println(hxrt::dynamic::from(xs.len() as i32));
}
