// Generated by reflaxe.rust (POC)

pub const __HX_TYPE_ID: u32 = 0xbc62c7dcu32;

#[derive(Debug)]

pub struct Base {}

impl Base {
    pub fn new() -> crate::HxRef<crate::base::Base> {
        let self_: crate::HxRef<crate::base::Base> = crate::HxRef::new(Base {});
        return self_;
    }

    pub fn f(_self_: &crate::HxRefCell<Base>, x: i32) -> i32 {
        return x + 1;
    }
}

pub trait BaseTrait: Send + Sync {
    fn f(&self, x: i32) -> i32;
    fn __hx_type_id(&self) -> u32;
}

impl crate::base::BaseTrait for crate::HxRefCell<Base> {
    fn f(&self, x: i32) -> i32 {
        Base::f(self, x)
    }
    fn __hx_type_id(&self) -> u32 {
        crate::base::__HX_TYPE_ID
    }
}
