// Generated by reflaxe.rust (POC)

#![allow(dead_code)]

type HxRef<T> = std::rc::Rc<std::cell::RefCell<T>>;

mod native_math;
mod sys;

fn main() {
    println!("{}", hxrt::dynamic::from(crate::native_math::gcd(54, 24)));
}
